import type { RecipeDefinition } from '../core/types';

export const RECIPES: Record<string, RecipeDefinition> = {
  workshop_pickaxe:{id:'workshop_pickaxe',resultItemId:'pickaxe',resultCount:1,ingredients:{wood:40,metal:15},requiredWorkbenchLevel:1,requiredTech:'efficiencyTooling',category:'Tools',craftTime:2},
  workshop_dressings:{id:'workshop_dressings',resultItemId:'bandage',resultCount:5,ingredients:{fiber:60},requiredWorkbenchLevel:2,requiredTech:'fieldMedicine',category:'Survival',craftTime:4},
  workshop_lights:{id:'workshop_lights',resultItemId:'torch',resultCount:3,ingredients:{wood:50,fiber:15},requiredWorkbenchLevel:3,requiredTech:'workshopLighting',category:'Tools',craftTime:3},
  storage:{id:'storage',resultItemId:'storage',resultCount:1,ingredients:{wood:160,fiber:20},category:'Building',craftTime:3},
  furnace:{id:'furnace',resultItemId:'furnace',resultCount:1,ingredients:{stone:200,wood:100,fiber:30},category:'Building',craftTime:5},
  campfire:{id:'campfire',resultItemId:'campfire',resultCount:1,ingredients:{stone:35,wood:40},category:'Survival',craftTime:2},
  bedroll:{id:'bedroll',resultItemId:'bedroll',resultCount:1,ingredients:{fiber:80,wood:20},category:'Survival',craftTime:3},
  bow:{id:'bow',resultItemId:'bow',resultCount:1,ingredients:{wood:90,fiber:35,hide:2},category:'Tools',craftTime:5},
  arrow:{id:'arrow',resultItemId:'arrow',resultCount:5,ingredients:{wood:20,stone:12,fiber:4},category:'Tools',craftTime:3},
  field_spear:{id:'field_spear',resultItemId:'spear',resultCount:1,ingredients:{wood:75,stone:45,fiber:20},requiredWorkbenchLevel:1,requiredTech:'fieldEngineering',category:'Tools',craftTime:5},
  field_generator:{id:'field_generator',resultItemId:'generator',resultCount:1,ingredients:{metal:90,wiring:8,machineParts:3},requiredWorkbenchLevel:2,requiredTech:'advancedFabrication',category:'Utilities',craftTime:9},
  field_switch:{id:'field_switch',resultItemId:'powerSwitch',resultCount:1,ingredients:{wood:20,metal:18,wiring:4},requiredWorkbenchLevel:2,requiredTech:'advancedFabrication',category:'Utilities',craftTime:4},
  field_lamp:{id:'field_lamp',resultItemId:'lamp',resultCount:1,ingredients:{metal:15,wiring:5},requiredWorkbenchLevel:3,requiredTech:'workshopLighting',category:'Utilities',craftTime:4},
  salvage_vest:{id:'salvage_vest',resultItemId:'salvageVest',resultCount:1,ingredients:{metal:85,machineParts:2,gears:2,fiber:45,hide:8},requiredWorkbenchLevel:2,requiredTech:'advancedFabrication',category:'Equipment',craftTime:8},
  field_revolver:{id:'field_revolver',resultItemId:'salvageRevolver',resultCount:1,ingredients:{metal:90,machineParts:3,gears:2,wood:20},requiredWorkbenchLevel:2,requiredTech:'advancedFabrication',category:'Weapons',craftTime:9},
  homestead_core:{id:'homestead_core',resultItemId:'homesteadCore',resultCount:1,ingredients:{metal:55,wiring:4,gears:2,scrap:30},requiredWorkbenchLevel:2,requiredTech:'advancedFabrication',category:'Building',craftTime:8},
  pistol_cartridges:{id:'pistol_cartridges',resultItemId:'pistolAmmo',resultCount:8,ingredients:{metal:18,sulfurOre:8,scrap:3},requiredWorkbenchLevel:2,requiredTech:'advancedFabrication',category:'Ammunition',craftTime:4},
  tidal_shotgun:{id:'tidal_shotgun',resultItemId:'fieldShotgun',resultCount:1,ingredients:{metal:120,machineParts:4,gears:3,wood:35},requiredWorkbenchLevel:3,requiredTech:'armoryEngineering',category:'Weapons',craftTime:12},
  shotgun_shells:{id:'shotgun_shells',resultItemId:'shotgunShells',resultCount:6,ingredients:{metal:16,sulfurOre:10,scrap:5},requiredWorkbenchLevel:3,requiredTech:'armoryEngineering',category:'Ammunition',craftTime:5},
  workbench1:{id:'workbench1',resultItemId:'workbench1',resultCount:1,ingredients:{wood:250,metal:40},category:'Building',craftTime:6},
  workbench2:{id:'workbench2',resultItemId:'workbench2',resultCount:1,ingredients:{wood:350,metal:150},requiredWorkbenchLevel:1,requiredTech:'workbench2Research',category:'Building',craftTime:8},
  workbench3:{id:'workbench3',resultItemId:'workbench3',resultCount:1,ingredients:{wood:500,metal:350},requiredWorkbenchLevel:2,requiredTech:'workbench3Research',category:'Building',craftTime:10},
  reinforced_storage:{id:'reinforced_storage',resultItemId:'storage',resultCount:1,ingredients:{wood:240,metal:50},requiredWorkbenchLevel:2,requiredTech:'advancedFabrication',category:'Building',craftTime:5},

  hatchet: { id: 'hatchet', resultItemId: 'hatchet', resultCount: 1, ingredients: { wood: 90, stone: 60, fiber: 10 }, category: 'Tools', craftTime: 3 },
  pickaxe: { id: 'pickaxe', resultItemId: 'pickaxe', resultCount: 1, ingredients: { wood: 90, stone: 90, fiber: 10 }, category: 'Tools', craftTime: 3 },
  hammer: { id: 'hammer', resultItemId: 'hammer', resultCount: 1, ingredients: { wood: 50, metal: 12 }, category: 'Tools', craftTime: 2.5 },
  plan: { id: 'plan', resultItemId: 'plan', resultCount: 1, ingredients: { wood: 25, fiber: 10 }, category: 'Building', craftTime: 1.5 },
  bandage: { id: 'bandage', resultItemId: 'bandage', resultCount: 1, ingredients: { fiber: 20 }, category: 'Survival', craftTime: 2 },
  canteen: { id: 'canteen', resultItemId: 'canteen', resultCount: 1, ingredients: { fiber: 35, metal: 8 }, category: 'Survival', craftTime: 3 },
  torch: { id: 'torch', resultItemId: 'torch', resultCount: 1, ingredients: { wood: 30, fiber: 10 }, category: 'Tools', craftTime: 2 },
};
