import type {GameState} from '../core/types';
import {ensureTech,TECH_NODES,type TechNodeId,type ResearchResult} from './techTree';
import type {Station} from '../survival/stations';
import './tech-tree.css';

export interface TechTreeActions{research:(id:TechNodeId)=>ResearchResult;close:()=>void}
const esc=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class TechTreeUI{
  readonly root=document.createElement('section');private state:GameState|null=null;private station:Station|null=null;private actions:TechTreeActions;private hash='';
  constructor(container:HTMLElement,actions:TechTreeActions){this.actions=actions;this.root.className='tech-tree-overlay';this.root.hidden=true;container.append(this.root);this.root.addEventListener('click',event=>{const target=(event.target as HTMLElement).closest<HTMLElement>('[data-tech-action]');if(!target)return;const action=target.dataset.techAction;if(action==='close')this.actions.close();if(action==='research'&&target.dataset.techId){const result=this.actions.research(target.dataset.techId as TechNodeId);this.hash='';if(!result.ok)this.flash(this.reason(result));}});}
  get isOpen(){return !this.root.hidden;}
  open(station:Station,state:GameState){this.station=station;this.state=state;this.root.hidden=false;this.hash='';this.render();}
  close(){this.root.hidden=true;this.station=null;this.state=null;this.hash='';}
  update(state:GameState){if(!this.isOpen)return;this.state=state;this.render();}
  private reason(result:ResearchResult){return result.reason==='resources'?`NOT ENOUGH SCRAP · ${result.node?.scrapCost} REQUIRED · ${result.remainingScrap??0} CARRIED`:result.reason==='workbench'?`WORKBENCH LEVEL ${result.node?.requiredWorkbenchLevel} REQUIRED`:result.reason==='prerequisite'?'PREREQUISITE LOCKED':result.reason==='already-unlocked'?'ALREADY UNLOCKED':'RESEARCH UNAVAILABLE';}
  private flash(message:string){const note=document.createElement('p');note.className='tech-tree-notice';note.textContent=message;this.root.querySelector('.tech-tree-shell')?.prepend(note);window.setTimeout(()=>note.remove(),2600);}
  private render(){if(!this.state||!this.station)return;const tech=ensureTech(this.state),level=Math.max(1,Number(this.station.kind.slice(-1))||1);const scrap=this.state.inventory.reduce((n,x)=>n+(x?.itemId==='scrap'?x.count:0),0);const cards=([1,2,3] as const).map(tier=>`<section class="tech-tier"><header><span>TECH TIER ${tier}</span><b>${tier<=level?'AVAILABLE':'REQUIRES WORKBENCH '+tier}</b></header><div class="tech-node-grid">${Object.values(TECH_NODES).filter(node=>node.tier===tier).map(node=>{const unlocked=tech.unlocked.includes(node.id),prereq=node.prerequisites.every(id=>tech.unlocked.includes(id)),bench=level>=node.requiredWorkbenchLevel,available=!unlocked&&prereq&&bench&&scrap>=node.scrapCost;const state=unlocked?'unlocked':!bench?'workbench':!prereq?'prerequisite':scrap<node.scrapCost?'resources':'available';const label=unlocked?'✓ UNLOCKED':!bench?'🔒 REQUIRES WORKBENCH '+node.requiredWorkbenchLevel:!prereq?'🔒 MISSING PREREQUISITE':scrap<node.scrapCost?'◇ NOT ENOUGH SCRAP':'◇ AVAILABLE';return `<article class="tech-node ${state}"><div class="tech-node-top"><span>TIER ${node.tier}</span><b>${node.scrapCost} SCRAP</b></div><h3>${esc(node.displayName)}</h3><p>${esc(node.description)}</p><small>UNLOCKS · ${node.unlocksRecipes.join(', ')}</small><strong>${label}</strong>${available?`<button data-tech-action="research" data-tech-id="${node.id}">RESEARCH</button>`:''}</article>`;}).join('')}</div></section>`).join('');this.root.innerHTML=`<div class="tech-tree-shell"><header class="tech-tree-header"><div><span class="eyebrow">TIDELAND / WORKBENCH RESEARCH</span><h2>TECH TREE</h2><p>Workbench level ${level} · Research knowledge persists with this world.</p></div><button data-tech-action="close">CLOSE · ESC</button></header><div class="tech-tree-summary"><span>SCRAP</span><b>${scrap}</b><span>WORKBENCH LEVEL</span><b>${level}</b></div>${cards}</div>`;}
}
