import {describe,it,expect} from 'vitest';import {createStation,tickStation,transfer,takeAll,stationStatus,validateStations,nearbyWorkbench} from '../src/survival/stations';import {GameSimulation} from '../src/simulation/GameSimulation';import {ensureProgression,upgrade,repair,demolish} from '../src/survival/progression';import {validateGameState} from '../src/save/storage';
const pos={x:0,y:5,z:0};
describe('survival progression',()=>{
it('transfers and splits using shared inventory core without crossing independent boxes',()=>{const g=new GameSimulation(1,pos),a=createStation('a','storage',pos),b=createStation('b','storage',pos);g.state.inventory[4]={itemId:'wood',count:9};expect(transfer(g.state.inventory,a,{container:'player',slot:4},{container:'station',slot:0},true,p=>g.fitsQueue(p))).toBe(true);expect(a.inventory[0]?.count).toBe(5);expect(g.state.inventory[4]?.count).toBe(4);expect(b.inventory[0]).toBe(null);takeAll(g.state.inventory,a,p=>g.fitsQueue(p));expect(g.count('wood')).toBe(9);});
it('reserves processing inputs once, persists midway and blocks without losing output',()=>{let s=createStation('f','furnace',pos);s.inventory[0]={itemId:'ore',count:20};s.inventory[2]={itemId:'wood',count:10};s.active=true;tickStation(s,3);expect(s.inventory[0]?.count).toBe(10);expect(s.job?.remaining).toBe(5);s=JSON.parse(JSON.stringify(s));s.inventory[3]={itemId:'metal',count:1000};s.inventory[4]={itemId:'metal',count:1000};tickStation(s,10);expect(stationStatus(s)).toBe('BLOCKED_OUTPUT_FULL');expect(s.inventory[0]?.count).toBe(10);s.inventory[4]=null;tickStation(s,.1);expect(s.inventory.slice(4)[0]?.count).toBe(10);expect(s.inventory[0]).toBe(null);expect(s.job?.remaining).toBeCloseTo(7.9);s.active=false;tickStation(s,100);expect(s.job?.remaining).toBeCloseTo(7.9);expect(validateStations([s])).toBe(true);});
it('rejects fuel/input mismatch, output deposits and malformed saved jobs',()=>{const g=new GameSimulation(2,pos),s=createStation('f','furnace',pos),fire=createStation('fire','campfire',pos);g.state.inventory[3]={itemId:'wood',count:10};expect(transfer(g.state.inventory,s,{container:'player',slot:3},{container:'station',slot:0},false,()=>true)).toBe(false);expect(transfer(g.state.inventory,s,{container:'player',slot:3},{container:'station',slot:3},false,()=>true)).toBe(false);g.state.inventory[4]={itemId:'cookedMeat',count:1};expect(transfer(g.state.inventory,fire,{container:'player',slot:4},{container:'station',slot:2},false,()=>true)).toBe(false);s.job={recipe:'metal',remaining:99};expect(validateStations([s])).toBe(false);});
it('gates progression by nearby bench and preserves older saves with no expansion',()=>{const g=new GameSimulation(3,pos);g.addItem('wood',1000);g.addItem('metal',1000);expect(g.canCraft('workbench2')).toBe(false);const p=ensureProgression(g.state);p.stations.push(createStation('station-1','workbench1',pos));g.state.nextId=2;g.addItem('scrap',80);expect(g.researchTech('workbench2Research').ok).toBe(true);expect(g.canCraft('workbench2')).toBe(true);expect(nearbyWorkbench(p.stations,{x:20,y:5,z:0})).toBe(0);expect(validateGameState(g.state)).toBe(true);delete g.state.progression;expect(validateGameState(g.state)).toBe(true);expect(new GameSimulation(3,pos,g.state).state.progression?.stations).toEqual([]);});
it('upgrades and repairs grade health and refuses demolition of supports',()=>{const g=new GameSimulation(4,pos);g.addItem('stone',1000);const s={id:'structure-1',pieceType:'foundation' as const,position:pos,rotation:0,health:250,createdAt:0};g.state.structures.push(s);g.state.nextId=2;expect(upgrade(g.state,s)).toBe(true);expect(s.health).toBe(600);s.health=300;expect(repair(g.state,s)).toBe(true);expect(s.health).toBe(600);expect(validateGameState(g.state)).toBe(true);g.state.structures.push({...s,id:'child',parentId:s.id});expect(demolish(g.state,s.id)).toBe(false);});
it('cooks raw meat over a persistent campfire and lets the player eat the result',()=>{const g=new GameSimulation(5,pos),s=createStation('fire','campfire',pos);s.inventory[0]={itemId:'wood',count:2};s.inventory[1]={itemId:'rawMeat',count:1};s.active=true;ensureProgression(g.state).stations.push(s);g.state.inventory[6]={itemId:'rawMeat',count:1};expect(g.consume(6)).toBe(false);g.state.inventory[6]=null;tickStation(s,4);expect(s.job).toEqual({recipe:'cook',remaining:8});expect(s.inventory[0]?.count).toBe(1);expect(s.inventory[1]).toBeNull();const saved=JSON.parse(JSON.stringify(g.state));expect(validateGameState(saved)).toBe(true);const loaded=new GameSimulation(5,pos,saved),fire=loaded.state.progression!.stations[0]!;tickStation(fire,8);expect(fire.inventory[2]).toEqual({itemId:'cookedMeat',count:1});loaded.state.player.stats.hunger=30;loaded.state.inventory[6]=fire.inventory[2];fire.inventory[2]=null;expect(loaded.consume(6)).toBe(true);expect(loaded.state.player.stats.hunger).toBe(54);});
it('keeps legacy one-slot campfire saves valid and expands them only in memory',()=>{const g=new GameSimulation(6,pos),s=createStation('old-fire','campfire',pos);s.inventory=[{itemId:'wood',count:3}];ensureProgression(g.state).stations.push(s);expect(validateGameState(g.state)).toBe(true);const loaded=new GameSimulation(6,pos,g.state),fire=loaded.state.progression!.stations[0]!;expect(fire.inventory).toHaveLength(3);expect(fire.inventory[0]).toEqual({itemId:'wood',count:3});expect(fire.inventory.slice(1)).toEqual([null,null]);expect(validateGameState(loaded.state)).toBe(true);});
it('does not consume fuel or raw meat when the cooked-meat output is full',()=>{const s=createStation('full-fire','campfire',pos);s.inventory[0]={itemId:'wood',count:2};s.inventory[1]={itemId:'rawMeat',count:1};s.inventory[2]={itemId:'cookedMeat',count:20};s.active=true;expect(stationStatus(s)).toBe('BLOCKED_OUTPUT_FULL');tickStation(s,20);expect(s.inventory[0]?.count).toBe(2);expect(s.inventory[1]?.count).toBe(1);expect(s.job).toBeNull();expect(validateStations([s])).toBe(true);});
});
