import {describe,it,expect} from 'vitest';import {createStation,tickStation,transfer,takeAll,stationStatus,validateStations,nearbyWorkbench} from '../src/survival/stations';import {GameSimulation} from '../src/simulation/GameSimulation';import {ensureProgression,upgrade,repair,demolish} from '../src/survival/progression';import {validateGameState} from '../src/save/storage';
const pos={x:0,y:5,z:0};
describe('survival progression',()=>{
it('transfers and splits using shared inventory core without crossing independent boxes',()=>{const g=new GameSimulation(1,pos),a=createStation('a','storage',pos),b=createStation('b','storage',pos);g.state.inventory[4]={itemId:'wood',count:9};expect(transfer(g.state.inventory,a,{container:'player',slot:4},{container:'station',slot:0},true,p=>g.fitsQueue(p))).toBe(true);expect(a.inventory[0]?.count).toBe(5);expect(g.state.inventory[4]?.count).toBe(4);expect(b.inventory[0]).toBe(null);takeAll(g.state.inventory,a,p=>g.fitsQueue(p));expect(g.count('wood')).toBe(9);});
it('reserves processing inputs once, persists midway and blocks without losing output',()=>{let s=createStation('f','furnace',pos);s.inventory[0]={itemId:'ore',count:20};s.inventory[2]={itemId:'wood',count:10};s.active=true;tickStation(s,3);expect(s.inventory[0]?.count).toBe(10);expect(s.job?.remaining).toBe(5);s=JSON.parse(JSON.stringify(s));s.inventory[3]={itemId:'metal',count:1000};s.inventory[4]={itemId:'metal',count:1000};tickStation(s,10);expect(stationStatus(s)).toBe('BLOCKED_OUTPUT_FULL');expect(s.inventory[0]?.count).toBe(10);s.inventory[4]=null;tickStation(s,.1);expect(s.inventory.slice(4)[0]?.count).toBe(10);expect(s.inventory[0]).toBe(null);expect(s.job?.remaining).toBeCloseTo(7.9);s.active=false;tickStation(s,100);expect(s.job?.remaining).toBeCloseTo(7.9);expect(validateStations([s])).toBe(true);});
it('rejects fuel/input mismatch, output deposits and malformed saved jobs',()=>{const g=new GameSimulation(2,pos),s=createStation('f','furnace',pos);g.state.inventory[3]={itemId:'wood',count:10};expect(transfer(g.state.inventory,s,{container:'player',slot:3},{container:'station',slot:0},false,()=>true)).toBe(false);expect(transfer(g.state.inventory,s,{container:'player',slot:3},{container:'station',slot:3},false,()=>true)).toBe(false);s.job={recipe:'metal',remaining:99};expect(validateStations([s])).toBe(false);});
it('gates progression by nearby bench and preserves older saves with no expansion',()=>{const g=new GameSimulation(3,pos);g.addItem('wood',1000);g.addItem('metal',1000);expect(g.canCraft('workbench2')).toBe(false);const p=ensureProgression(g.state);p.stations.push(createStation('station-1','workbench1',pos));g.state.nextId=2;expect(g.canCraft('workbench2')).toBe(true);expect(nearbyWorkbench(p.stations,{x:20,y:5,z:0})).toBe(0);expect(validateGameState(g.state)).toBe(true);delete g.state.progression;expect(validateGameState(g.state)).toBe(true);expect(new GameSimulation(3,pos,g.state).state.progression?.stations).toEqual([]);});
it('upgrades and repairs grade health and refuses demolition of supports',()=>{const g=new GameSimulation(4,pos);g.addItem('stone',1000);const s={id:'structure-1',pieceType:'foundation' as const,position:pos,rotation:0,health:250,createdAt:0};g.state.structures.push(s);g.state.nextId=2;expect(upgrade(g.state,s)).toBe(true);expect(s.health).toBe(600);s.health=300;expect(repair(g.state,s)).toBe(true);expect(s.health).toBe(600);expect(validateGameState(g.state)).toBe(true);g.state.structures.push({...s,id:'child',parentId:s.id});expect(demolish(g.state,s.id)).toBe(false);});
});
