import {describe,it,expect} from 'vitest';
import {GameSimulation} from '../src/simulation/GameSimulation';
import {createStation} from '../src/survival/stations';
import {ensureProgression} from '../src/survival/progression';
import {TECH_NODES,ensureTech,grandfatherUnlocks} from '../src/crafting/techTree';
import {RECIPES} from '../src/crafting/recipes';
import {validateGameState} from '../src/save/storage';
const pos={x:0,y:5,z:0};
const bench=(level:1|2|3)=>createStation(`bench-${level}`,`workbench${level}`,pos);
describe('v0.8.0 tech tree progression',()=>{
  it('new game starts with empty persistent tech knowledge and basic recipes',()=>{const g=new GameSimulation(1,pos);expect(g.state.progression?.tech).toEqual({version:1,unlocked:[]});expect(g.canCraft('hatchet')).toBe(false);expect(RECIPES.hatchet.requiredTech).toBeUndefined();expect(g.canCraft('workshop_pickaxe')).toBe(false);});
  it('research spends exact Scrap atomically and unlocks recipe',()=>{const g=new GameSimulation(2,pos);ensureProgression(g.state).stations.push(bench(1));g.addItem('scrap',50);const result=g.researchTech('efficiencyTooling');expect(result.ok).toBe(true);expect(g.count('scrap')).toBe(15);expect(g.state.progression?.tech?.unlocked).toEqual(['efficiencyTooling']);expect(g.craftStatus('workshop_pickaxe').reason).toBe('resources');});
  it('unlocks the field spear through Field Engineering while preserving workbench and save requirements',()=>{const g=new GameSimulation(22,pos);ensureProgression(g.state).stations.push(bench(1));expect(g.canCraft('field_spear')).toBe(false);g.addItem('scrap',50);expect(g.researchTech('fieldEngineering').ok).toBe(true);g.addItem('wood',75);g.addItem('stone',45);g.addItem('fiber',20);expect(g.canCraft('field_spear')).toBe(true);expect(g.craft('field_spear')).toBe(true);g.tick(5,false);expect(g.count('spear')).toBe(1);expect(validateGameState(g.state)).toBe(true);});
  it('insufficient Scrap, missing bench and prerequisite never consume',()=>{const g=new GameSimulation(3,pos);g.addItem('scrap',34);expect(g.researchTech('efficiencyTooling').reason).toBe('workbench');ensureProgression(g.state).stations.push(bench(1));expect(g.researchTech('efficiencyTooling').reason).toBe('resources');expect(g.count('scrap')).toBe(34);expect(g.researchTech('fieldMedicine').reason).toBe('prerequisite');});
  it('research is idempotent under rapid duplicate calls',()=>{const g=new GameSimulation(4,pos);ensureProgression(g.state).stations.push(bench(1));g.addItem('scrap',70);expect(g.researchTech('efficiencyTooling').ok).toBe(true);expect(g.researchTech('efficiencyTooling').reason).toBe('already-unlocked');expect(g.count('scrap')).toBe(35);expect(g.state.progression?.tech?.unlocked).toHaveLength(1);});
  it('higher workbench does not bypass prerequisites',()=>{const g=new GameSimulation(5,pos);ensureProgression(g.state).stations.push(bench(3));g.addItem('scrap',1000);expect(g.researchTech('fieldMedicine').reason).toBe('prerequisite');expect(g.researchTech('workbench3Research').reason).toBe('prerequisite');expect(g.researchTech('efficiencyTooling').ok).toBe(true);});
  it('tier one is available at workbench II and III',()=>{for(const level of [2,3] as const){const g=new GameSimulation(level,pos);ensureProgression(g.state).stations.push(bench(level));g.addItem('scrap',100);expect(g.researchTech('efficiencyTooling').ok).toBe(true);}});
  it('full progression unlocks every paid node in order',()=>{const g=new GameSimulation(6,pos);ensureProgression(g.state).stations.push(bench(3));g.addItem('scrap',1000);for(const id of ['efficiencyTooling','workbench2Research','fieldMedicine','advancedFabrication','workbench3Research','workshopLighting','armoryEngineering'] as const)expect(g.researchTech(id).ok).toBe(true);expect(g.state.progression?.tech?.unlocked).toEqual(['efficiencyTooling','workbench2Research','fieldMedicine','advancedFabrication','workbench3Research','workshopLighting','armoryEngineering']);});
  it('research unlocks a workbench-gated field generator, switch and lamp craft chain',()=>{const g=new GameSimulation(63,pos);ensureProgression(g.state).stations.push(bench(3));g.addItem('scrap',1000);for(const id of ['workbench2Research','advancedFabrication','workbench3Research','workshopLighting'] as const)expect(g.researchTech(id).ok).toBe(true);g.addItem('wood',20);g.addItem('metal',200);g.addItem('wiring',20);g.addItem('machineParts',5);expect(g.canCraft('field_generator')).toBe(true);expect(g.canCraft('field_switch')).toBe(true);expect(g.canCraft('field_lamp')).toBe(true);for(const id of ['field_generator','field_switch','field_lamp'])expect(g.craft(id)).toBe(true);g.tick(9,false);expect(g.count('generator')).toBe(1);g.tick(4,false);expect(g.count('powerSwitch')).toBe(1);g.tick(4,false);expect(g.count('lamp')).toBe(1);expect(validateGameState(g.state)).toBe(true);});
  it('recipes retain physical workbench requirement after unlock',()=>{const g=new GameSimulation(7,pos);ensureProgression(g.state).stations.push(bench(1));g.addItem('scrap',35);g.researchTech('efficiencyTooling');g.addItem('wood',100);g.addItem('metal',100);expect(g.canCraft('workshop_pickaxe')).toBe(true);g.state.player.position={x:20,y:5,z:0};expect(g.craftStatus('workshop_pickaxe').reason).toBe('workbench');});
  it('legacy saves migrate once by highest existing Workbench',()=>{for(const level of [0,1,2,3] as const){const g=new GameSimulation(8,pos);const p=ensureProgression(g.state);if(level)p.stations.push(bench(level));delete p.tech;const migrated=ensureTech(g.state);expect(migrated.unlocked).toEqual(grandfatherUnlocks(level));const again=ensureTech(g.state);expect(again.unlocked).toEqual(migrated.unlocked);}}
  );
  it('does not grant new tier-three armory research when migrating a pre-update workbench save',()=>{expect(grandfatherUnlocks(3)).not.toContain('armoryEngineering');});
  it('tech knowledge survives death and save validation round trip',()=>{const g=new GameSimulation(9,pos);ensureProgression(g.state).stations.push(bench(1));g.addItem('scrap',35);expect(g.researchTech('efficiencyTooling').ok).toBe(true);const saved=structuredClone(g.state);expect(validateGameState(saved)).toBe(true);const reloaded=new GameSimulation(9,pos,saved);expect(reloaded.state.progression?.tech?.unlocked).toEqual(['efficiencyTooling']);});
  it('validator accepts old saves and rejects malformed tech state',()=>{const g=new GameSimulation(10,pos);const old=structuredClone(g.state);delete old.progression;expect(validateGameState(old)).toBe(true);const unknown=structuredClone(g.state);unknown.progression!.tech={version:1,unlocked:['unknown' as never]};expect(validateGameState(unknown)).toBe(false);const duplicate=structuredClone(g.state);duplicate.progression!.tech={version:1,unlocked:['efficiencyTooling','efficiencyTooling']};expect(validateGameState(duplicate)).toBe(false);const badVersion=structuredClone(g.state);badVersion.progression!.tech={version:2 as 1,unlocked:[]};expect(validateGameState(badVersion)).toBe(false);});
  it('armory research gates and crafts the shotgun and its ammunition',()=>{const g=new GameSimulation(73,pos);ensureProgression(g.state).stations.push(bench(3));g.addItem('scrap',1000);expect(g.canCraft('tidal_shotgun')).toBe(false);for(const id of ['workbench2Research','advancedFabrication','workbench3Research'] as const)expect(g.researchTech(id).ok).toBe(true);g.addItem('metal',150);g.addItem('machineParts',6);g.addItem('gears',3);g.addItem('wood',35);g.addItem('sulfurOre',10);g.addItem('scrap',5);expect(g.researchTech('armoryEngineering').ok).toBe(true);expect(g.canCraft('tidal_shotgun')).toBe(true);expect(g.canCraft('shotgun_shells')).toBe(true);expect(g.craft('tidal_shotgun')).toBe(true);expect(g.craft('shotgun_shells')).toBe(true);g.tick(12,false);g.tick(5,false);expect(g.count('fieldShotgun')).toBe(1);expect(g.count('shotgunShells')).toBe(6);expect(validateGameState(g.state)).toBe(true);});
  it('advanced fabrication unlocks a durable salvage vest without changing save version',()=>{const g=new GameSimulation(74,pos);ensureProgression(g.state).stations.push(bench(2));g.addItem('scrap',170);expect(g.researchTech('workbench2Research').ok).toBe(true);expect(g.researchTech('advancedFabrication').ok).toBe(true);expect(g.canCraft('salvage_vest')).toBe(false);g.addItem('metal',85);g.addItem('machineParts',2);g.addItem('gears',2);g.addItem('fiber',45);g.addItem('hide',8);expect(g.canCraft('salvage_vest')).toBe(true);expect(g.craft('salvage_vest')).toBe(true);g.tick(8,false);expect(g.state.inventory.find(stack=>stack?.itemId==='salvageVest')?.condition).toBeUndefined();expect(g.state.progression?.tech?.unlocked).toContain('advancedFabrication');expect(g.state.version).toBe(1);expect(validateGameState(structuredClone(g.state))).toBe(true);});
  it('recipe requirements match the tree contract',()=>{for(const node of Object.values(TECH_NODES))for(const recipeId of node.unlocksRecipes){const recipe=RECIPES[recipeId];expect(recipe).toBeTruthy();if(recipe.requiredTech)expect(recipe.requiredTech).toBe(node.id);}}
  );
});
