import type { ItemDefinition, ItemId } from '../core/types';

const item = (id: ItemId, displayName: string, description: string, category: ItemDefinition['category'], maxStack: number, tags: string[], extra: Partial<ItemDefinition> = {}): ItemDefinition => ({ id, displayName, description, category, maxStack, tags, icon: `assets/icons/${id}.svg`, ...extra });

export const ITEMS: Record<ItemId, ItemDefinition> = {
  ore: item('ore', 'Metal ore', 'Dense iron-bearing ore collected from mineral nodes. Process it at a field processor.', 'resource', 1000, ['survival'], {placeable:false}),
  sulfurOre: item('sulfurOre', 'Sulfur ore', 'Bright sulfur-bearing rock gathered from rare yellow mineral deposits.', 'resource', 1000, ['survival','crafting'], {placeable:false}),
  hqMetalOre: item('hqMetalOre', 'High quality metal ore', 'A rare dense metallic ore found in the richest dark mineral deposits.', 'resource', 250, ['survival','crafting'], {placeable:false}),
  scrap: item('scrap', 'Scrap', 'Sorted salvage with enough value to support advanced island progression.', 'resource', 1000, ['scrap','progression','salvage'], {placeable:false}),
  gears: item('gears', 'Gears', 'Recovered mechanical gearing from abandoned equipment.', 'resource', 100, ['component','salvage'], {placeable:false}),
  wiring: item('wiring', 'Wiring', 'Insulated electrical wiring salvaged from old equipment.', 'resource', 100, ['component','salvage'], {placeable:false}),
  machineParts: item('machineParts', 'Machine Parts', 'Precision mechanical pieces useful for advanced fabrication.', 'resource', 100, ['component','salvage'], {placeable:false}),
  techParts: item('techParts', 'Tech Parts', 'Rare sealed technical modules recovered from high-value salvage.', 'resource', 50, ['component','salvage'], {placeable:false}),
  storage: item('storage', 'Storage box', 'Place from your hotbar; E opens 18 slots.', 'building', 1, ['survival'], {placeable:true}),
  furnace: item('furnace', 'Field processor', 'Converts raw resources into game crafting fragments.', 'building', 1, ['survival'], {placeable:true}),
  workbench1: item('workbench1', 'Workbench level 1', 'Unlocks recipes while standing within 5 meters.', 'building', 1, ['survival'], {placeable:true}),
  workbench2: item('workbench2', 'Workbench level 2', 'A more capable workshop.', 'building', 1, ['survival'], {placeable:true}),
  workbench3: item('workbench3', 'Workbench level 3', 'Advanced crafting station.', 'building', 1, ['survival'], {placeable:true}),
  bedroll: item('bedroll', 'Sleeping roll', 'Place and interact to choose your respawn point.', 'utility', 1, ['survival'], {placeable:true}),
  generator: item('generator','Field generator','A salvaged petrol-electric unit. Load wood fuel and connect a nearby switch.','utility',1,['power','building'],{placeable:true}),
  powerSwitch: item('powerSwitch','Field switch','Routes a nearby powered generator to lamps within its local range.','utility',1,['power','building'],{placeable:true}),
  lamp: item('lamp','Caged utility lamp','A weathered low-voltage lamp for a powered field shelter.','utility',1,['power','building'],{placeable:true}),
  rock: item('rock', 'Weathered rock', 'A dependable starting tool. Strike trees and mineral deposits to gather resources.', 'tool', 1, ['gather', 'starter']),
  torch: item('torch', 'Handmade torch', 'A resin-soaked torch. Equip it after sundown to illuminate your surroundings.', 'tool', 1, ['light', 'starter']),
  wood: item('wood', 'Wood', 'Timber gathered from trees and driftwood. The foundation of a new shelter.', 'resource', 1000, ['building', 'crafting']),
  stone: item('stone', 'Stone', 'Rough stone used in foundations and improvised tools.', 'resource', 1000, ['building', 'crafting']),
  metal: item('metal', 'Metal fragments', 'Processed fragments used for hardware and stronger construction.', 'resource', 1000, ['crafting']),
  fiber: item('fiber', 'Plant fiber', 'Tough fibers from wild flax. Twist into cord or use as a dressing.', 'resource', 1000, ['crafting']),
  berries: item('berries', 'Wild berries', 'A small meal that restores 9 food and 5 hydration. Double-click to eat.', 'food', 20, ['food'], { consumable: true }),
  rawMeat: item('rawMeat', 'Raw meat', 'Freshly recovered island game. Cook it over a campfire before eating.', 'resource', 20, ['food','cooking']),
  hide: item('hide', 'Animal hide', 'Weathered hide recovered from hunted wildlife. Useful for field clothing.', 'resource', 50, ['crafting','equipment']),
  shirt: item('shirt','Flax field shirt','A light woven layer with modest protection against scrapes.','utility',1,['equipment']),
  pants: item('pants','Work trousers','Durable field trousers that soften impacts and protect against rough ground.','utility',1,['equipment']),
  boots: item('boots','Hide boots','Insulated boots for cold ground and rough terrain.','utility',1,['equipment']),
  warmJacket: item('warmJacket','Insulated jacket','A thick salvage-lined jacket that meaningfully slows cold exposure.','utility',1,['equipment','warmth']),
  protectiveHood: item('protectiveHood','Filter hood','A sealed field hood that offers limited protection from contaminated air.','utility',1,['equipment','hazard']),
  salvageVest: item('salvageVest','Salvage plate vest','A padded torso rig backed with recovered plate sections. It softens gunfire and blows, but offers little insulation.','utility',1,['equipment','armor','salvage']),
  yardPlate: item('yardPlate','Quarry plate rig','A reinforced industrial torso rig cut from quarry machinery guards. Strong against bullets and impacts, with no weather insulation.','utility',1,['equipment','armor','industrial']),
  bow: item('bow','Island hunting bow','A simple ash-and-fiber bow. Hold primary fire to draw, then release to loose an arrow.','tool',1,['weapon','ranged']),
  spear: item('spear','Salvage-tipped spear','A long field haft with a hardened salvage point. Its reach is useful against wildlife, but the narrow thrust needs a steady aim.','tool',1,['weapon','melee']),
  docksideCleaver: item('docksideCleaver','Dockside cleaver','A short, heavy salvage blade rebuilt from a cargo-handling tool. Quicker and broader than a spear, with less reach.','tool',1,['weapon','melee','salvage']),
  quarryMaul: item('quarryMaul','Quarry maul','A slow industrial breaker built from quarry steel and a reinforced timber haft. Its heavy head hits hard, but demands room and stamina.','tool',1,['weapon','melee','industrial']),
  arrow: item('arrow','Field arrow','A recoverable wood-shaft arrow with a forged salvage point.','resource',100,['ammunition','crafting']),
  salvageRevolver:item('salvageRevolver','Salvage revolver','A hand-fitted six-shot sidearm assembled from recovered industrial parts. Press R to reload.','tool',1,['weapon','firearm','ranged']),
  fieldShotgun:item('fieldShotgun','Tidal salvage shotgun','A heavy four-shell break-action field gun with a broad close-range spread. Press R to reload.','tool',1,['weapon','firearm','ranged']),
  pistolAmmo:item('pistolAmmo','Pistol cartridges','Low-pressure cartridges assembled from recovered metal and sulfur.','resource',48,['ammunition','crafting']),
  shotgunShells:item('shotgunShells','Shotgun shells','Compact game ammunition loaded for the Tidal salvage shotgun.','resource',32,['ammunition','crafting']),
  relayAccessCard:item('relayAccessCard','Relay access card','A recovered industrial access card for sealed high-value island caches.','utility',2,['key','salvage']),
  homesteadCore:item('homesteadCore','Homestead beacon','A salvaged property marker that claims a modest shelter area and secures its doors.','building',1,['building','ownership'],{placeable:true}),
  hatchet: item('hatchet', 'Stone hatchet', 'A hafted cutting edge. Gathers wood two and a half times as quickly.', 'tool', 1, ['gather', 'wood']),
  pickaxe: item('pickaxe', 'Stone pickaxe', 'A rugged mining tool. Gathers stone and metal two and a half times as quickly.', 'tool', 1, ['gather', 'mining']),
  hammer: item('hammer', 'Builder\'s hammer', 'A compact field hammer for inspecting, upgrading, repairing and safely removing structures.', 'tool', 1, ['building','maintenance']),
  plan: item('plan', 'Building plan', 'Equip to place foundations, walls, doorways, doors, floors and roofs. Press B to choose a piece.', 'building', 1, ['build']),
  bandage: item('bandage', 'Field dressing', 'Clean plant-fiber dressing. Restores 24 health. Double-click to use.', 'utility', 5, ['healing'], { consumable: true }),
  traumaKit: item('traumaKit', 'Trauma kit', 'A sealed advanced field kit. Restores 48 health. Double-click to use.', 'utility', 2, ['healing','medical'], { consumable: true }),
  canteen: item('canteen', 'Rainwater pouch', 'A small collector of fresh water. Restores 42 hydration. Double-click to drink.', 'utility', 3, ['water'], { consumable: true }),
  campfire: item('campfire', 'Campfire kit', 'A bundle of fuel and stones prepared for a sheltered fire.', 'utility', 1, ['camp'], { placeable: true }),
};

export function isItemId(value: unknown): value is ItemId {
  return typeof value === 'string' && Object.hasOwn(ITEMS, value);
}
