import type {ItemId,Language} from '../core/types';
import {ITEMS} from './definitions';

const cs:Record<ItemId,string>={
  ore:'Železná ruda',sulfurOre:'Sirná ruda',hqMetalOre:'Vysoce kvalitní ruda',scrap:'Šrot',gears:'Ozubená kola',wiring:'Vodiče',machineParts:'Strojní součástky',techParts:'Technické moduly',
  storage:'Úložná bedna',furnace:'Polní pec',workbench1:'Pracovní stůl I',workbench2:'Pracovní stůl II',workbench3:'Pracovní stůl III',bedroll:'Spací vak',generator:'Polní generátor',powerSwitch:'Polní vypínač',lamp:'Kryté pracovní světlo',
  rock:'Ošlehaný kámen',torch:'Ruční pochodeň',wood:'Dřevo',stone:'Kámen',metal:'Kovové úlomky',fiber:'Rostlinné vlákno',berries:'Lesní plody',rawMeat:'Syrové maso',cookedMeat:'Pečené maso',hide:'Zvířecí kůže',
  shirt:'Plátěná košile',pants:'Pracovní kalhoty',boots:'Kožené boty',warmJacket:'Zateplená bunda',protectiveHood:'Filtrační kukla',salvageVest:'Záchranářská vesta',yardPlate:'Lomová plátová vesta',bow:'Lovecký luk',spear:'Oštěp ze šrotu',docksideCleaver:'Přístavní sekáček',quarryMaul:'Lomové kladivo',arrow:'Polní šíp',salvageRevolver:'Revolver ze šrotu',fieldShotgun:'Pobřežní brokovnice',pistolAmmo:'Náboje do pistole',shotgunShells:'Brokové náboje',relayAccessCard:'Přístupová karta vysílače',homesteadCore:'Maják usedlosti',
  hatchet:'Kamenná sekera',pickaxe:'Kamenný krumpáč',hammer:'Stavební kladivo',plan:'Stavební plán',bandage:'Polní obvaz',traumaKit:'Traumatická souprava',canteen:'Vak na dešťovou vodu',campfire:'Táborový oheň'
};

const csDescription:Record<ItemId,string>={
  ore:'Hutná železná ruda z ložisek. Zpracuj ji v polní peci.',sulfurOre:'Sirná ruda z neobvyklých žlutých ložisek.',hqMetalOre:'Vzácná hustá ruda z nejbohatších tmavých ložisek.',scrap:'Roztříděný šrot, který pomáhá s pokročilým vybavením ostrova.',gears:'Ozubená soukolí zachráněná ze starých strojů.',wiring:'Izolované vodiče ze zchátralého vybavení.',machineParts:'Přesné strojní díly pro pokročilejší výrobu.',techParts:'Vzácné zapečetěné moduly z cenných nalezišť.',
  storage:'Umísti bednu z rychlé výbavy. Klávesou E otevřeš 18 míst.',furnace:'Zpracovává suroviny na úlomky potřebné k výrobě.',workbench1:'Zpřístupní recepty, když stojíš do 5 metrů.',workbench2:'Pokročilejší dílna pro náročnější výrobu.',workbench3:'Vyspělá výrobní stanice pro nejpokročilejší recepty.',
  shirt:'Lehká lněná vrstva, která mírně chrání před odřeninami.',pants:'Odolné pracovní kalhoty, které tlumí nárazy a chrání před terénem.',
  bow:'Jednoduchý luk z jasanu a vláken. Podrž útok pro napnutí, puštěním vystřelíš.',arrow:'Šíp s dřevěným tělem a kovaným hrotem. Lze ho sebrat.',docksideCleaver:'Krátká těžká čepel přestavěná z nákladního nářadí. Je rychlá, ale má kratší dosah.',quarryMaul:'Pomalé bourací kladivo z lomové oceli a zesílené násady. Má velkou sílu a potřebuje prostor.',pistolAmmo:'Náboje s nízkým tlakem vyrobené z kovu a síry.',shotgunShells:'Kompaktní brokové náboje pro pobřežní brokovnici.',relayAccessCard:'Získaná přístupová karta k uzamčeným zásobám s vysokou hodnotou.',
  rock:'Spolehlivý základní nástroj. Těž zdroje ze stromů a ložisek.',torch:'Pochodeň napuštěná pryskyřicí. Po setmění si ji vezmi do ruky.',wood:'Dřevo ze stromů a naplavenin. Základ pro první přístřešek.',stone:'Hrubý kámen na základy a provizorní nástroje.',metal:'Zpracované úlomky pro spojovací materiál a odolnější stavby.',fiber:'Pevná vlákna z divokého lnu. Hodí se na provazy i obvazy.',berries:'Drobné jídlo, které doplní 9 jídla a 5 vody. Dvojklikem sníš.',rawMeat:'Čerstvé maso z ostrovní zvěře. Než ho sníš, upeč ho na ohni.',cookedMeat:'Teplé jídlo z táboráku. Po snědení doplní 24 jídla.',hide:'Vydělaná kůže z ulovené zvěře. Používá se na polní oblečení.',
  hatchet:'Sekera na násadě. Dřevo získáš dvaapůlkrát rychleji.',pickaxe:'Odolný těžební nástroj. Kámen a kov získáš dvaapůlkrát rychleji.',hammer:'Polní kladivo pro kontrolu, vylepšení, opravy a bezpečné odstranění staveb.',plan:'Vybav plán a umisťuj základy, stěny, dveře, podlahy i střechy.',bandage:'Čistý obvaz z rostlinných vláken. Obnoví 24 zdraví.',traumaKit:'Zapečetěná zdravotnická souprava. Obnoví 48 zdraví.',canteen:'Vak s čerstvou vodou. Doplní 42 hydratace.',campfire:'Připravené palivo a kameny pro chráněné ohniště.',
  generator:'Zachráněný benzínový generátor. Přidej palivo a připoj vypínač.',powerSwitch:'Přepíná blízký generátor pro pracovní světla v dosahu.',lamp:'Oprýskané nízkonapěťové světlo pro napájený přístřešek.',bedroll:'Umísti ho a vyber si nové místo pro návrat po smrti.',
  salvageRevolver:'Ruční šestiranná pistole ze zachráněných dílů. R pro nabití.',fieldShotgun:'Těžká čtyřranná zlamovací brokovnice. R pro nabití.',spear:'Dlouhá násada s hrotem ze šrotu. Má dobrý dosah, ale vyžaduje přesné míření.',
  homesteadCore:'Maják vymezí prostor přístřešku a zabezpečí jeho dveře.',
  boots:'Zateplené boty do studené půdy a náročného terénu.',warmJacket:'Silná bunda s výstelkou ze záchranářské výbavy, zpomaluje prochladnutí.',protectiveHood:'Utěsněná kukla s omezenou ochranou před znečištěným vzduchem.',salvageVest:'Polstrovaná vesta s plátovými díly. Tlumí zásahy, ale málo hřeje.',yardPlate:'Zesílená vesta z krytů lomových strojů. Chrání před střelami a nárazy, ne před chladem.',
};

export function itemName(id:ItemId,language:Language):string{return language==='cs'?(cs[id]??ITEMS[id].displayName):ITEMS[id].displayName;}
export function itemDescription(id:ItemId,language:Language,english:string):string{return language==='cs'?csDescription[id]:english;}
