import * as THREE from 'three';
import type {EffectQuality,GraphicsQuality,ShadowQuality} from '../core/types';
import {mountainLayer} from './horizon';

export class Atmosphere {
  readonly sky:THREE.Mesh<THREE.SphereGeometry,THREE.ShaderMaterial>;
  readonly ocean:THREE.Mesh<THREE.PlaneGeometry,THREE.ShaderMaterial>;
  readonly sun=new THREE.DirectionalLight(0xfff0ce,3.1);
  readonly fill=new THREE.HemisphereLight(0xbacfe0,0x525944,2.1);
  readonly fog=new THREE.FogExp2(0xb1c6cf,.00145);
  readonly horizon=new THREE.Group();private horizonGeometries:THREE.BufferGeometry[]=[];private horizonMaterials:THREE.Material[]=[];
  readonly sunDirection=new THREE.Vector3(-.5,.72,.4).normalize();
  private readonly illuminationDirection=new THREE.Vector3();
  private elapsed=0;private daylight=1;private underwaterTarget=0;private underwater=0;private readonly underwaterTint=new THREE.Color(0x18424d);
  private readonly mist={value:0};
  private readonly stormTint=new THREE.Color(.29,.27,.38);private readonly mountainTint=new THREE.Color();
  get daylightAmount(){return this.daylight;}

  constructor(readonly scene:THREE.Scene,heightTexture:THREE.DataTexture,readonly terrainSize=720,private readonly seed=731942,private readonly worldRevision=5){
    this.sky=new THREE.Mesh(new THREE.SphereGeometry(1600,40,20),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{sunDir:{value:this.sunDirection},daylight:{value:1},clock:{value:0},weather:{value:0},storm:{value:0},lightning:{value:0},mist:this.mist,mistTint:{value:this.fog.color}},vertexShader:`varying vec3 vDirection;void main(){vDirection=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`
      varying vec3 vDirection;uniform vec3 sunDir;uniform float daylight;uniform float clock;uniform float weather;uniform float storm;uniform float lightning;uniform float mist;uniform vec3 mistTint;
      float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+1.),f.x),f.y);}float fbm(vec2 p){float f=0.;f+=.5*noise(p);p=p*2.03+17.2;f+=.25*noise(p);p=p*2.01-12.7;f+=.125*noise(p);p=p*2.04+8.2;f+=.0625*noise(p);return f;}
      void main(){vec3 d=normalize(vDirection);float altitude=max(d.y,0.);float horizonHaze=pow(1.-altitude,5.);vec3 horizon=mix(vec3(.045,.065,.115),vec3(.49,.70,.84),daylight);vec3 zenith=mix(vec3(.008,.015,.048),vec3(.075,.31,.69),daylight);horizon=mix(horizon,vec3(.35,.29,.46),weather*.62);zenith=mix(zenith,vec3(.12,.16,.29),weather*.50);vec3 col=mix(horizon,zenith,pow(altitude,.46));col=mix(col,vec3(.43,.42,.53),horizonHaze*weather*.42);vec3 stormSky=mix(vec3(.018,.026,.045),vec3(.12,.15,.19),daylight);col=mix(col,stormSky,storm*.70);
        float alignment=max(0.,dot(d,sunDir)),sunset=(1.-smoothstep(.04,.45,sunDir.y))*smoothstep(-.2,.1,sunDir.y);col+=vec3(.42,.12,.025)*pow(alignment,5.)*sunset;col+=vec3(1.,.84,.57)*pow(alignment,110.)*.38*daylight;col+=vec3(1.,.95,.80)*smoothstep(.99935,.99982,alignment)*daylight*5.;
        vec3 moonDir=-sunDir;float moon=max(0.,dot(d,moonDir));col+=vec3(.56,.67,.86)*smoothstep(.99945,.99982,moon)*(1.-daylight)*1.35;col+=vec3(.15,.20,.31)*pow(moon,55.)*(1.-daylight)*.22;
        vec2 baseUv=d.xz/max(.10,d.y+.075)*2.55,drift=vec2(clock*.0018,clock*.00045);float broad=fbm(baseUv*.58+drift),detail=fbm(baseUv*1.43+drift*1.7+11.),high=fbm(baseUv*2.4-drift*.8-23.);float cloudField=broad*.50+detail*.42+high*.15;float cloud=smoothstep(.52-weather*.07-storm*.10,.72-weather*.12-storm*.20,cloudField);float stormMass=noise(baseUv*.24+drift*.22+vec2(41.,-17.));float stormCover=smoothstep(.24,.76,stormMass)*smoothstep(.012,.16,d.y);cloud=max(cloud,stormCover*.88*storm);cloud*=smoothstep(.012,.16,d.y);float lining=pow(max(0.,dot(normalize(vec3(d.x,.16,d.z)),sunDir)),7.)*cloud;vec3 cloudDark=mix(vec3(.025,.035,.065),vec3(.58,.64,.67),daylight);vec3 cloudLight=mix(cloudDark,vec3(.98,.96,.86),daylight);vec3 cloudColor=mix(cloudDark,cloudLight,smoothstep(.44,.78,broad));cloudColor+=vec3(1.,.78,.48)*lining*sunset*.45;cloudColor=mix(cloudColor,vec3(.11,.13,.16),weather*.90);vec3 stormCloud=mix(vec3(.028,.038,.056),vec3(.052,.064,.082)+stormMass*vec3(.065,.07,.075),daylight);cloudColor=mix(cloudColor,stormCloud,storm*.94);col=mix(col,cloudColor,min(.97,cloud*(.77+weather*.20+storm*.12)));
        float wisps=smoothstep(.57,.73,fbm(baseUv*.25-drift*.35+vec2(73.,-41.)))*smoothstep(.06,.35,d.y)*(1.-smoothstep(.62,.92,d.y));col=mix(col,vec3(.93,.97,1.),wisps*.19*daylight*(1.-weather*.55));col+=vec3(.62,.72,.90)*lightning*(.18+.82*cloud);float stars=step(.9942,hash(floor(d.xz/max(.055,d.y)*620.)))*smoothstep(.045,.4,d.y)*(1.-daylight)*(1.-cloud*.78);col+=stars*vec3(.88,.94,1.);col=mix(col,mistTint,1.-exp(-mist*mist*48.*exp(-altitude*8.)));gl_FragColor=vec4(col,1.);#include <tonemapping_fragment>\n#include <colorspace_fragment>}`.replace(';#include',';\n#include')}));
    this.sky.frustumCulled=false;this.sky.renderOrder=-10;scene.add(this.sky);this.buildHorizon();scene.add(this.horizon);

    const oceanSize=terrainSize>720?4400:2600,oceanGeo=new THREE.PlaneGeometry(oceanSize,oceanSize,176,176);oceanGeo.rotateX(-Math.PI/2);
    this.ocean=new THREE.Mesh(oceanGeo,new THREE.ShaderMaterial({side:THREE.DoubleSide,uniforms:{clock:{value:0},weather:{value:0},storm:{value:0},underwater:{value:0},waterDetail:{value:1},revision6:{value:worldRevision>=6?1:0},sunDir:{value:this.sunDirection},cameraPos:{value:new THREE.Vector3()},daylight:{value:1},heightMap:{value:heightTexture},islandSize:{value:terrainSize},fogColor:{value:this.fog.color}},vertexShader:`uniform float clock;uniform float weather;uniform float storm;uniform float revision6;varying vec3 vWorld;void main(){vec3 p=position;p.y+=sin(p.x*.095+p.z*.043+clock*.55)*.10+sin(p.z*.077-p.x*.023+clock*.38)*.11+sin(p.x*.037-p.z*.12-clock*.46)*.07;p.y+=weather*sin(p.x*.06+p.z*.04+clock)*.18;p.y+=storm*sin(p.x*.014-p.z*.021+clock*.28)*.30;p.y+=revision6*(sin(p.x*.024+p.z*.017+clock*.21)*.13+sin(p.z*.018-p.x*.009-clock*.17)*.08+sin(p.x*.032+p.z*.009+clock*.18)*.55+sin(p.z*.019-p.x*.014-clock*.13)*.32);vWorld=(modelMatrix*vec4(p,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`
      uniform float clock;uniform float weather;uniform float storm;uniform float underwater;uniform float waterDetail;uniform float revision6;uniform vec3 sunDir;uniform vec3 cameraPos;uniform float daylight;uniform sampler2D heightMap;uniform float islandSize;uniform vec3 fogColor;varying vec3 vWorld;
      float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1.,0.)),f.x),mix(h(i+vec2(0.,1.)),h(i+vec2(1.,1.)),f.x),f.y);}float waves(vec2 p){vec2 d=vec2(clock*.13,-clock*.19);float s=n(p*.16+d*.4);float choppy=n(p*.72+d+s)*.78+n(mat2(.8,.6,-.6,.8)*p*1.7-d)*mix(.24,.36,waterDetail);if(waterDetail>.4)choppy+=n(p*4.3+d*1.3)*.11;float baseWaves=sin(p.x*.095+p.y*.043+clock*.55)*.10+sin(p.y*.077-p.x*.023+clock*.38)*.11+sin(p.x*.037-p.y*.12-clock*.46)*.07+weather*sin(p.x*.06+p.y*.04+clock)*.18+storm*sin(p.x*.014-p.y*.021+clock*.28)*.30;float revisionWaves=revision6*(sin(p.x*.024+p.y*.017+clock*.21)*.13+sin(p.y*.018-p.x*.009-clock*.17)*.08+sin(p.x*.032+p.y*.009+clock*.18)*.55+sin(p.y*.019-p.x*.014-clock*.13)*.32);return choppy+baseWaves+revisionWaves;}
      void main(){vec2 p=vWorld.xz;float w=waves(p),near=1.-smoothstep(55.,270.,length(cameraPos.xz-p));float eps=mix(.30,.14,waterDetail),normalScale=near*(.72+waterDetail*.28+storm*.75);vec3 normal=normalize(vec3((waves(p-vec2(eps,0.))-waves(p+vec2(eps,0.)))*normalScale,1.22,(waves(p-vec2(0.,eps))-waves(p+vec2(0.,eps)))*normalScale));vec3 view=normalize(cameraPos-vWorld);float fres=pow(1.-max(.0,dot(normal,view)),3.25);vec3 deep=mix(vec3(.014,.055,.075),vec3(.032,.14,.16),daylight);vec3 skyReflect=mix(vec3(.025,.045,.095),vec3(.31,.48,.60),daylight);deep=mix(deep,vec3(.055,.055,.12),weather*.58);skyReflect=mix(skyReflect,vec3(.22,.18,.34),weather*.50);vec3 water=mix(deep,skyReflect,.04+fres*.42*(1.-underwater*.92));float spec=pow(max(0.,dot(reflect(-sunDir,normal),view)),95.);water+=vec3(1.,.82,.53)*spec*(1.15+fres)*daylight*(1.-underwater*.92);
        vec2 huv=p/islandSize+.5;float terrain=texture2D(heightMap,huv).r*100.-20.;float bounds=step(0.,huv.x)*step(huv.x,1.)*step(0.,huv.y)*step(huv.y,1.);float shore=abs(terrain-vWorld.y),shallow=(1.-smoothstep(0.,4.8,-terrain))*bounds;vec3 shallows=vec3(.045,.235,.25)*(.35+.65*daylight);water=mix(water,shallows,shallow*(1.-fres*.72)*.70);float ripple=sin(p.x*.17+p.y*.075+clock*1.25)*sin(p.y*.13-p.x*.045-clock*.87);water+=vec3(.008,.025,.027)*ripple*(.35+near*.65)*(1.-weather*.35)*mix(.18,1.,waterDetail);vec2 rainCell=floor(p*.31),rainLocal=fract(p*.31)-.5;vec2 rainCenter=vec2(h(rainCell+vec2(13.1,4.7)),h(rainCell+vec2(7.2,19.6)))-.5;float rainAge=fract(clock*.28+h(rainCell+vec2(2.4,8.3)));float rainRing=(1.-smoothstep(.012,.055,abs(length(rainLocal-rainCenter)-rainAge*.42)))*(1.-smoothstep(.72,1.,rainAge))*weather*waterDetail;water+=vec3(.012,.025,.028)*rainRing;float foamNoise=n(p*3.2+vec2(clock*.19,-clock*.11));if(waterDetail>.4)foamNoise=foamNoise*.62+n(p*7.7-clock*.07)*.38;float foamEdge=shore+(foamNoise-.5)*.46+sin(p.x*.34+p.y*.27+clock*.55)*.10;float band=(1.-smoothstep(-.12,1.05,foamEdge))*bounds;float foam=band*smoothstep(.40,.76,foamNoise+sin(shore*7.-clock*1.4)*.13);water=mix(water,vec3(.82,.87,.82)*(.35+.65*daylight),foam*(.58+.20*waterDetail)*(1.-underwater));float stormCrest=smoothstep(.70,1.08,w+sin(p.x*.047+p.y*.061+clock*.34)*.08)*storm*(.065+near*.13);water=mix(water,vec3(.62,.70,.68)*(.50+.50*daylight),stormCrest);water=mix(water,vec3(.018,.095,.12),underwater*.78);float dist=length(cameraPos-vWorld);float haze=1.-exp(-dist*(.00165+underwater*.018));water=mix(water,mix(fogColor,vec3(.025,.11,.14),underwater*.82),haze);gl_FragColor=vec4(water,1.);#include <tonemapping_fragment>\n#include <colorspace_fragment>}`.replace(';#include',';\n#include')}));
    this.ocean.position.y=-.12;this.ocean.receiveShadow=true;scene.add(this.ocean);

    this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.camera.left=this.sun.shadow.camera.bottom=-72;this.sun.shadow.camera.right=this.sun.shadow.camera.top=72;this.sun.shadow.camera.near=.5;this.sun.shadow.camera.far=225;this.sun.shadow.bias=-.00016;this.sun.shadow.normalBias=.055;this.sun.shadow.radius=3;scene.add(this.sun,this.sun.target,this.fill);scene.fog=this.fog;
  }

  private buildHorizon():void{
    for(let layer=2;layer>=0;layer--){
      const g=mountainLayer(this.seed,layer,this.terrainSize>720,this.worldRevision),material={color:0x8299a8,vertexColors:true,depthWrite:false,side:THREE.DoubleSide,fog:false},m=this.worldRevision>=6?new THREE.MeshLambertMaterial({...material,emissive:0x384755,emissiveIntensity:.22}):new THREE.MeshBasicMaterial(material);
      if(this.worldRevision>=6){
        // Blend opaque distant terrain into the same mist as the low sky;
        // scene fog alone leaves bright cutouts against an unaffected sky.
        m.onBeforeCompile=shader=>{
          shader.uniforms.mist=this.mist;shader.uniforms.mistTint={value:this.fog.color};
          shader.fragmentShader='uniform float mist;uniform vec3 mistTint;\n'+shader.fragmentShader.replace('#include <tonemapping_fragment>','gl_FragColor.rgb=mix(gl_FragColor.rgb,mistTint,1.-exp(-mist*mist*48.));\n#include <tonemapping_fragment>');
        };
        m.customProgramCacheKey=()=> 'rev6-horizon-mist-v1';
      }
      const mesh=new THREE.Mesh(g,m);mesh.name=`Distant massif layer ${layer}`;mesh.userData.layer=layer;mesh.renderOrder=-5;mesh.frustumCulled=false;this.horizon.add(mesh);this.horizonGeometries.push(g);this.horizonMaterials.push(m);
    }
  }

  update(dt:number,time:number,camera:THREE.Vector3):void{
    this.elapsed+=dt;const a=(time-6)/24*Math.PI*2;this.sunDirection.set(-Math.cos(a)*.75,Math.sin(a),.42).normalize();this.daylight=THREE.MathUtils.smoothstep(this.sunDirection.y,-.16,.26);
    this.sun.intensity=.28+this.daylight*2.50;this.sun.color.setRGB(.52+this.daylight*.48,.62+this.daylight*.31,.88+this.daylight*.19);this.fill.intensity=1.42+this.daylight*.58;this.fill.color.setRGB(.60+this.daylight*.10,.67+this.daylight*.09,.86+this.daylight*.06);this.fill.groundColor.setRGB(.42+this.daylight*.05,.45+this.daylight*.05,.52);
    this.underwater=THREE.MathUtils.damp(this.underwater,this.underwaterTarget,3,dt);const weather=this.sky.material.uniforms.weather.value as number,storm=this.sky.material.uniforms.storm.value as number;this.fog.color.setRGB(.05+.48*this.daylight,.078+.55*this.daylight,.14+.61*this.daylight).lerp(this.stormTint,storm*.45).lerp(this.underwaterTint,this.underwater*.78);this.fog.density=.00105+(1-this.daylight)*.00162+storm*.00048+weather*.00012+this.underwater*.015;
    const sx=Math.round(camera.x/2)*2,sz=Math.round(camera.z/2)*2;this.sun.target.position.set(sx,camera.y-5,sz);this.illuminationDirection.copy(this.sunDirection).multiplyScalar(this.daylight).addScaledVector(this.sunDirection,-(1-this.daylight)).normalize();this.sun.position.copy(this.sun.target.position).addScaledVector(this.illuminationDirection,105);this.sky.position.copy(camera);this.horizon.position.set(camera.x,camera.y-28,camera.z);
    this.sky.material.uniforms.daylight.value=this.daylight;this.sky.material.uniforms.clock.value=this.elapsed;this.ocean.material.uniforms.clock.value=this.elapsed;this.ocean.material.uniforms.daylight.value=this.daylight;this.ocean.material.uniforms.cameraPos.value.copy(camera);this.ocean.material.uniforms.storm.value=storm;this.ocean.material.uniforms.underwater.value=this.underwater;this.horizonMaterials.forEach((m,i)=>{const layer=2-i,basic=m as THREE.MeshBasicMaterial|THREE.MeshLambertMaterial;basic.color.setRGB(.055+this.daylight*(.22+layer*.065),.075+this.daylight*(.30+layer*.06),.12+this.daylight*(.35+layer*.055)).multiplyScalar(.68+layer*.12);if(this.worldRevision>=6){const distanceMist=.22+(2-layer)*.13;basic.color.lerp(this.fog.color,distanceMist*this.daylight);}this.mountainTint.setRGB(.07+this.daylight*.10,.08+this.daylight*.12,.12+this.daylight*.16);basic.color.lerp(this.mountainTint,storm*.78);const sunset=(1-this.daylight)*Math.max(0,this.sunDirection.y+.16);basic.color.r+=sunset*.2;if(basic instanceof THREE.MeshLambertMaterial)basic.emissiveIntensity=.16+(1-this.daylight)*.68+storm*.10;});
  }

  setSubmerged(cameraHeight:number):void{this.underwaterTarget=this.underwaterTarget>.5?(cameraHeight>.28?0:1):(cameraHeight<-.38?1:0);}

  setMist(amount:number):void{this.mist.value=this.worldRevision>=6?THREE.MathUtils.clamp(amount,0,1):0;}

  setWaterQuality(q:EffectQuality):void{this.ocean.material.uniforms.waterDetail.value=q==='low'?.35:q==='medium'?.68:1;}
  setQuality(q:GraphicsQuality):void{
    this.sun.castShadow=q!=='low';const size=q==='ultra'?3072:q==='high'?2048:q==='medium'?1024:768;this.sun.shadow.radius=q==='ultra'?4:q==='high'?3:2;
    if(this.sun.shadow.mapSize.x!==size){this.sun.shadow.mapSize.set(size,size);this.sun.shadow.map?.dispose();this.sun.shadow.map=null;}
  }
  setShadowSettings(enabled:boolean,quality:ShadowQuality,distance:number):void{
    this.sun.castShadow=enabled;const size=quality==='high'?3072:quality==='medium'?2048:1024,d=Math.max(35,Math.min(120,distance));this.sun.shadow.radius=quality==='high'?4:quality==='medium'?3:2;
    this.sun.shadow.camera.left=this.sun.shadow.camera.bottom=-d;this.sun.shadow.camera.right=this.sun.shadow.camera.top=d;this.sun.shadow.camera.far=Math.max(150,d*3.1);this.sun.shadow.camera.updateProjectionMatrix();
    if(this.sun.shadow.mapSize.x!==size){this.sun.shadow.mapSize.set(size,size);this.sun.shadow.map?.dispose();this.sun.shadow.map=null;}
  }
  dispose():void{this.sky.geometry.dispose();this.sky.material.dispose();this.ocean.geometry.dispose();this.ocean.material.dispose();for(const g of this.horizonGeometries)g.dispose();for(const m of this.horizonMaterials)m.dispose();this.scene.remove(this.sky,this.horizon,this.ocean,this.sun,this.sun.target,this.fill);this.sun.shadow.map?.dispose();}
}
