import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const outputDir=process.env.TIDELAND_QA_DIR||'test-results/combat';fs.mkdirSync(outputDir,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN,args:['--enable-webgl','--use-gl=angle',`--use-angle=${process.env.TIDELAND_QA_ANGLE||'swiftshader'}`]});
const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],checks=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
const pass=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS',name);};
const characterScreenshot=async name=>{const style=await page.addStyleTag({content:'.interaction-prompt,.crosshair{visibility:hidden!important}'});try{await page.screenshot({path:`${outputDir}/${name}.png`});}finally{await style.evaluate(element=>element.remove());}};
try{
  await page.goto(process.env.TIDELAND_QA_URL||'http://127.0.0.1:5173');await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});
  await page.locator('[data-action="new"]').click();await page.locator('[data-save-action="new"][data-save-slot="1"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});
  const selected=await page.evaluate(()=>{const a=window.__TIDELAND;a.setCapturePaused(true);const g=a.sim();g.state.inventory[0]={itemId:'rock',count:1};g.selectSlot(0);const actor=a.wildlife().find(x=>x.species==='islandWolf')??a.wildlife()[0];if(!actor)throw Error('No seeded wildlife generated');const x=actor.position.x-4.5,z=actor.position.z,p={x,y:a.height(x,z)+.06,z};a.teleport(p);a.lookAt({x:actor.position.x,y:actor.position.y+1.02,z:actor.position.z});a.configureWildlifeForTest(actor.id,{yaw:Math.atan2(p.x-actor.position.x,p.z-actor.position.z)});a.setCapturePaused(false);return {actor,position:p};});
  const boarId=await page.evaluate(()=>{const a=window.__TIDELAND,boar=a.wildlife().find(actor=>actor.species==='coastalBoar'&&actor.state!=='dead');if(!boar)return null;const x=boar.position.x-3.2,z=boar.position.z,p={x,y:a.height(x,z)+.06,z};a.setCapturePaused(true);a.teleport(p);a.lookAt({x:boar.position.x,y:boar.position.y+.78,z:boar.position.z});a.configureWildlifeForTest(boar.id,{yaw:Math.atan2(p.x-boar.position.x,p.z-boar.position.z)});a.setCapturePaused(false);return boar.id;});
  if(boarId){await page.waitForTimeout(80);await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));await characterScreenshot('coastal-boar-close');await page.evaluate(id=>{const a=window.__TIDELAND,boar=a.wildlife().find(actor=>actor.id===id),x=boar.position.x+3.2,z=boar.position.z,p={x,y:a.height(x,z)+.06,z};a.teleport(p);a.lookAt({x:boar.position.x,y:boar.position.y+.78,z:boar.position.z});a.configureWildlifeForTest(id,{yaw:0});a.setCapturePaused(false);},boarId);await page.waitForTimeout(80);await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));await characterScreenshot('coastal-boar-profile');}
  pass('Seeded wildlife spawned with a stable actor id',Boolean(selected.actor.id));await page.waitForTimeout(80);await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));await characterScreenshot('wildlife-close');await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(entry=>entry.id===id),x=actor.position.x+4.5,z=actor.position.z,y=a.height(x,z)+.06;a.teleport({x,y,z});a.lookAt({x:actor.position.x,y:actor.position.y+1.02,z:actor.position.z});a.configureWildlifeForTest(id,{yaw:0});a.setCapturePaused(false);},selected.actor.id);await page.waitForTimeout(80);await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));await characterScreenshot('wildlife-profile');
  await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id);a.lookAt({x:actor.position.x-8,y:actor.position.y+.68,z:actor.position.z});},selected.actor.id);await page.waitForTimeout(100);
  const miss=await page.evaluate(id=>{const a=window.__TIDELAND,g=a.sim(),actor=a.wildlife().find(x=>x.id===id),before=g.state.player.stats.stamina,condition=g.state.inventory[0]?.condition??null,healthBefore=actor?.health;a.strikeWildlife(id);return {before,after:g.state.player.stats.stamina,conditionBefore:condition,conditionAfter:g.state.inventory[0]?.condition??null,healthBefore,health:a.wildlife().find(x=>x.id===id)?.health};},selected.actor.id);pass('A committed miss spends stamina but preserves weapon condition and target health',miss.after===miss.before-5&&miss.conditionAfter===miss.conditionBefore&&miss.health===miss.healthBefore);
  await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id);a.teleport({x:actor.position.x-1.2,y:a.height(actor.position.x-1.2,actor.position.z)+.06,z:actor.position.z});a.lookAt({x:actor.position.x,y:actor.position.y+.68,z:actor.position.z});},selected.actor.id);await page.waitForTimeout(100);
  const first=await page.evaluate(id=>{const a=window.__TIDELAND,before=a.wildlife().find(actor=>actor.id===id)?.health;a.strikeWildlife(id);return {health:a.wildlife().find(actor=>actor.id===id)?.health,before};},selected.actor.id);pass('Aimed first-person melee swing damages wildlife',first.health<first.before);
  const spear=await page.evaluate(id=>{const a=window.__TIDELAND,g=a.sim(),actor=a.wildlife().find(x=>x.id===id);g.state.inventory[0]={itemId:'spear',count:1,condition:90};a.selectSlot(0);const x=actor.position.x-2.1,z=actor.position.z;a.teleport({x,y:a.height(x,z)+.06,z});a.lookAt({x:actor.position.x,y:actor.position.y+.68,z:actor.position.z});const before=actor.health;a.strikeWildlife(id);const after=a.wildlife().find(x=>x.id===id);return {before,after:after?.health,condition:g.state.inventory[0]?.condition,stagger:after?.staggerSeconds};},selected.actor.id);pass('Research-tier spear reaches wildlife from farther away, wears on impact and staggers the target',spear.after<spear.before&&spear.condition===89&&spear.stagger>0);await page.evaluate(()=>window.__TIDELAND.setCapturePaused(false));await page.waitForFunction(id=>window.__TIDELAND.wildlife().find(actor=>actor.id===id)?.state==='stagger',selected.actor.id,{timeout:3000});await page.screenshot({path:`${outputDir}/spear-stagger.png`});await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));pass('Strong melee impact has a readable stagger pose in the running game',true);
  const cleaver=await page.evaluate(id=>{const a=window.__TIDELAND,g=a.sim(),actor=a.wildlife().find(x=>x.id===id);g.state.inventory[0]={itemId:'docksideCleaver',count:1,condition:135};a.selectSlot(0);const x=actor.position.x-1.65,z=actor.position.z;a.teleport({x,y:a.height(x,z)+.06,z});a.lookAt({x:actor.position.x,y:actor.position.y+.68,z:actor.position.z});const before=actor.health;a.strikeWildlife(id);return {before,after:a.wildlife().find(x=>x.id===id)?.health,condition:g.state.inventory[0]?.condition,held:document.querySelector('.active-item-name')?.textContent};},selected.actor.id);pass('Advanced salvage cleaver hits wildlife, applies its damage and wears on contact',cleaver.after<cleaver.before&&cleaver.condition===134);await page.waitForTimeout(400);const heldName=await page.locator('.active-item-name').textContent();pass('First-person slot and HUD identify the equipped Dockside cleaver',heldName?.toUpperCase().includes('DOCKSIDE CLEAVER'));await page.screenshot({path:`${outputDir}/dockside-cleaver.png`});
  for(let hit=0;hit<6;hit++){const health=await page.evaluate(id=>window.__TIDELAND.wildlife().find(a=>a.id===id)?.health,selected.actor.id);if(health===undefined||health<=0)break;await page.waitForTimeout(700);await page.evaluate(id=>window.__TIDELAND.strikeWildlife(id),selected.actor.id);}
  const killed=await page.evaluate(id=>({dead:window.__TIDELAND.wildlife().find(a=>a.id===id)?.state==='dead',health:window.__TIDELAND.wildlife().find(a=>a.id===id)?.health,saved:window.__TIDELAND.snapshot().nodeChanges[id],inventory:window.__TIDELAND.snapshot().inventory.filter(Boolean).map(s=>s.itemId),drops:window.__TIDELAND.snapshot().drops.map(d=>d.stack.itemId)}),selected.actor.id);
  pass('Defeated wildlife state and meat/hide loot persist',killed.dead&&killed.health===0&&killed.saved===0&&(killed.inventory.includes('rawMeat')||killed.drops.includes('rawMeat'))&&(killed.inventory.includes('hide')||killed.drops.includes('hide')));
  const maul=await page.evaluate(()=>{const a=window.__TIDELAND,g=a.sim(),actor=a.wildlife().find(candidate=>candidate.state!=='dead');if(!actor)throw Error('No live target for quarry maul balance QA');a.setCapturePaused(true);g.state.player.stats.stamina=100;g.state.inventory[0]={itemId:'quarryMaul',count:1,condition:180};a.selectSlot(0);const x=actor.position.x-1.4,z=actor.position.z;a.teleport({x,y:a.height(x,z)+.06,z});a.lookAt({x:actor.position.x,y:actor.position.y+.68,z:actor.position.z});const health=actor.health;a.strikeWildlife(actor.id);return {before:health,after:a.wildlife().find(candidate=>candidate.id===actor.id)?.health,stamina:g.state.player.stats.stamina,condition:g.state.inventory[0]?.condition};});
  pass('Endgame Quarry Maul strike pays its stamina and heavy durability cost',maul.after<maul.before&&maul.stamina===78&&maul.condition===178);
  const attacker=await page.evaluate(()=>{const a=window.__TIDELAND,target=a.wildlife().find(actor=>actor.species==='islandWolf'&&actor.state!=='dead')??a.wildlife().find(actor=>actor.state!=='dead');if(!target)return null;const p={x:target.position.x-1.35,y:a.height(target.position.x-1.35,target.position.z)+.06,z:target.position.z};a.teleport(p);a.lookAt({x:target.position.x,y:target.position.y+.68,z:target.position.z});a.provokeWildlife(target.id);a.setCapturePaused(false);return {id:target.id,health:a.snapshot().player.stats.health};});assert.ok(attacker);await page.waitForFunction(health=>window.__TIDELAND.snapshot().player.stats.health<health,attacker.health,{timeout:12000});const afterAttack=await page.evaluate(()=>{window.__TIDELAND.setCapturePaused(true);return window.__TIDELAND.snapshot().player.stats.health;});pass('Angered wildlife can damage the player through typed combat',afterAttack<attacker.health&&afterAttack>0);
  await page.evaluate(()=>window.__TIDELAND.save());await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});
  pass('Hunted actor stays absent after save/reload',!(await page.evaluate(id=>window.__TIDELAND.wildlife().some(a=>a.id===id),selected.actor.id)));
  await page.evaluate(()=>{window.__TIDELAND.sim().state.inventory[7]={itemId:'warmJacket',count:1};window.__TIDELAND.save();});await page.keyboard.press('Tab');await page.locator('.inventory-backpack [data-slot="7"]').click();await page.locator('[data-action="wear"]').click();
  const worn=await page.evaluate(()=>({equipment:window.__TIDELAND.snapshot().player.equipment,health:window.__TIDELAND.snapshot().player.stats.health}));pass('Inventory equips crafted clothing into its slot',worn.equipment?.body==='warmJacket');
  const protectedHit=await page.evaluate(()=>{const a=window.__TIDELAND,before=a.snapshot().player.stats.health,result=a.applyPlayerDamage({amount:10,type:'cold',sourceId:'equipment-qa'}),state=a.snapshot();return {before,after:state.player.stats.health,condition:state.player.equipmentCondition?.body,result};});pass('Equipped jacket reduces cold damage at runtime',protectedHit.result.applied<10&&protectedHit.after===protectedHit.before-protectedHit.result.applied);pass('Environmental hits wear protective clothing condition',protectedHit.condition<115&&protectedHit.condition>0);const expectedGear=`B:Jacket ${Math.floor(protectedHit.condition)}/115`;await page.waitForFunction(text=>document.querySelector('.inventory-world-info')?.textContent?.includes(text),expectedGear,{timeout:3000});const gearText=(await page.locator('.inventory-world-info').textContent())??'';pass(`Inventory displays worn gear condition: ${gearText}`,gearText.includes(expectedGear));
  await page.screenshot({path:`${outputDir}/equipment-condition.png`});
  await page.evaluate(()=>window.__TIDELAND.save());await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});
  pass('Equipped clothing and remaining condition survive save/reload',await page.evaluate(condition=>{const state=window.__TIDELAND.snapshot();return state.player.equipment?.body==='warmJacket'&&state.player.equipmentCondition?.body===condition;},protectedHit.condition));
  await page.evaluate(()=>{window.__TIDELAND.sim().state.inventory[8]={itemId:'salvageVest',count:1};});await page.keyboard.press('Tab');await page.locator('.inventory-backpack [data-slot="8"]').click();await page.locator('[data-action="wear"]').click();await page.waitForFunction(condition=>{const state=window.__TIDELAND.snapshot();return state.player.equipment?.body==='salvageVest'&&state.inventory[8]?.itemId==='warmJacket'&&state.inventory[8]?.condition===condition;},protectedHit.condition,{timeout:5000});const armorSwap=await page.evaluate(()=>{const state=window.__TIDELAND.snapshot();return {equipped:state.player.equipment?.body,returned:state.inventory[8],condition:state.player.equipmentCondition?.body};});pass('Workbench-tier salvage vest replaces, but preserves, worn insulated clothing',armorSwap.equipped==='salvageVest'&&armorSwap.returned?.itemId==='warmJacket'&&armorSwap.returned.condition===protectedHit.condition);await page.waitForFunction(()=>document.querySelector('.character-art')?.getAttribute('data-body')==='salvageVest',null,{timeout:3000});pass('Inventory survivor illustration reflects equipped salvage armor',await page.locator('.character-art').getAttribute('data-body')==='salvageVest');const armorHit=await page.evaluate(()=>{const a=window.__TIDELAND,result=a.applyPlayerDamage({amount:20,type:'projectile',sourceId:'armor-qa'});return {applied:result.applied,condition:a.snapshot().player.equipmentCondition?.body};});pass('Salvage vest provides stronger projectile protection and wears under fire',armorHit.applied<17&&armorHit.condition<150);await page.screenshot({path:`${outputDir}/salvage-vest-equipped.png`});await page.evaluate(()=>window.__TIDELAND.save());await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});pass('Salvage vest and degraded condition survive save/reload',await page.evaluate(condition=>{const state=window.__TIDELAND.snapshot();return state.player.equipment?.body==='salvageVest'&&state.player.equipmentCondition?.body===condition;},armorHit.condition));
  await page.evaluate(()=>{window.__TIDELAND.sim().state.inventory[9]={itemId:'yardPlate',count:1};});await page.keyboard.press('Tab');await page.locator('.inventory-backpack [data-slot="9"]').click();await page.locator('[data-action="wear"]').click();pass('Industrial plate swaps into the body slot and returns the salvage vest',await page.evaluate(()=>{const state=window.__TIDELAND.snapshot();return state.player.equipment?.body==='yardPlate'&&state.inventory[9]?.itemId==='salvageVest';}));await page.waitForFunction(()=>document.querySelector('.character-art')?.getAttribute('data-body')==='yardPlate',null,{timeout:3000});pass('Inventory survivor illustration shows the industrial plate silhouette',await page.locator('.character-art').getAttribute('data-body')==='yardPlate');const plateHit=await page.evaluate(()=>{const a=window.__TIDELAND,projectile=a.applyPlayerDamage({amount:20,type:'projectile',sourceId:'plate-qa'}),cold=a.applyPlayerDamage({amount:10,type:'cold',sourceId:'plate-cold-qa'}),state=a.snapshot();return {projectile:projectile.applied,cold:cold.applied,condition:state.player.equipmentCondition?.body};});pass('Industrial plate improves projectile protection without adding cold insulation',plateHit.projectile<13.5&&plateHit.cold===10&&plateHit.condition<220);await page.evaluate(()=>window.__TIDELAND.save());await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});pass('Industrial plate and worn condition survive save/reload',await page.evaluate(condition=>{const state=window.__TIDELAND.snapshot();return state.player.equipment?.body==='yardPlate'&&state.player.equipmentCondition?.body===condition;},plateHit.condition));
  pass('No browser application or WebGL console errors',errors.length===0);
  fs.writeFileSync(`${outputDir}/results.json`,JSON.stringify({checks,errors,actorId:selected.actor.id,initialSpecies:selected.actor.species,firstHit:first.health,death:killed.saved},null,2));await page.screenshot({path:`${outputDir}/post-hunt.png`});
}finally{await browser.close();}
