import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const outputDir=process.env.TIDELAND_QA_DIR||'test-results/combat';fs.mkdirSync(outputDir,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN,args:['--enable-webgl','--use-gl=angle',`--use-angle=${process.env.TIDELAND_QA_ANGLE||'swiftshader'}`]});
const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],checks=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
const pass=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS',name);};
try{
  await page.goto(process.env.TIDELAND_QA_URL||'http://127.0.0.1:5173');await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});
  await page.locator('[data-action="new"]').click();await page.locator('[data-save-action="new"][data-save-slot="1"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});
  const selected=await page.evaluate(()=>{const a=window.__TIDELAND;a.setCapturePaused(true);const g=a.sim();g.state.inventory[0]={itemId:'rock',count:1};g.selectSlot(0);const actor=a.wildlife().find(x=>x.species==='islandWolf')??a.wildlife()[0];if(!actor)throw Error('No seeded wildlife generated');const x=actor.position.x-1.2,z=actor.position.z,p={x,y:a.height(x,z)+.06,z};a.teleport(p);a.lookAt({x:actor.position.x,y:actor.position.y+.68,z:actor.position.z});return {actor,position:p};});
  pass('Seeded wildlife spawned with a stable actor id',Boolean(selected.actor.id));await page.waitForTimeout(250);await page.screenshot({path:`${outputDir}/wildlife-close.png`});
  const first=await page.evaluate(id=>{const a=window.__TIDELAND,before=a.wildlife().find(actor=>actor.id===id)?.health;a.strikeWildlife(id);return {health:a.wildlife().find(actor=>actor.id===id)?.health,before};},selected.actor.id);pass('Aimed first-person melee swing damages wildlife',first.health<first.before);
  for(let hit=0;hit<6;hit++){const health=await page.evaluate(id=>window.__TIDELAND.wildlife().find(a=>a.id===id)?.health,selected.actor.id);if(health===undefined||health<=0)break;await page.waitForTimeout(700);await page.evaluate(id=>window.__TIDELAND.strikeWildlife(id),selected.actor.id);}
  const killed=await page.evaluate(id=>({dead:window.__TIDELAND.wildlife().find(a=>a.id===id)?.state==='dead',health:window.__TIDELAND.wildlife().find(a=>a.id===id)?.health,saved:window.__TIDELAND.snapshot().nodeChanges[id],inventory:window.__TIDELAND.snapshot().inventory.filter(Boolean).map(s=>s.itemId),drops:window.__TIDELAND.snapshot().drops.map(d=>d.stack.itemId)}),selected.actor.id);
  pass('Defeated wildlife state and meat/hide loot persist',killed.dead&&killed.health===0&&killed.saved===0&&(killed.inventory.includes('rawMeat')||killed.drops.includes('rawMeat'))&&(killed.inventory.includes('hide')||killed.drops.includes('hide')));
  const attacker=await page.evaluate(()=>{const a=window.__TIDELAND,target=a.wildlife().find(actor=>actor.species==='islandWolf'&&actor.state!=='dead')??a.wildlife().find(actor=>actor.state!=='dead');if(!target)return null;const p={x:target.position.x-1.35,y:a.height(target.position.x-1.35,target.position.z)+.06,z:target.position.z};a.teleport(p);a.lookAt({x:target.position.x,y:target.position.y+.68,z:target.position.z});a.provokeWildlife(target.id);a.setCapturePaused(false);return {id:target.id,health:a.snapshot().player.stats.health};});assert.ok(attacker);await page.waitForFunction(health=>window.__TIDELAND.snapshot().player.stats.health<health,attacker.health,{timeout:12000});const afterAttack=await page.evaluate(()=>{window.__TIDELAND.setCapturePaused(true);return window.__TIDELAND.snapshot().player.stats.health;});pass('Angered wildlife can damage the player through typed combat',afterAttack<attacker.health&&afterAttack>0);
  await page.evaluate(()=>window.__TIDELAND.save());await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});
  pass('Hunted actor stays absent after save/reload',!(await page.evaluate(id=>window.__TIDELAND.wildlife().some(a=>a.id===id),selected.actor.id)));
  await page.evaluate(()=>{window.__TIDELAND.sim().state.inventory[7]={itemId:'warmJacket',count:1};window.__TIDELAND.save();});await page.keyboard.press('Tab');await page.locator('.inventory-backpack [data-slot="7"]').click();await page.locator('[data-action="wear"]').click();
  const worn=await page.evaluate(()=>({equipment:window.__TIDELAND.snapshot().player.equipment,health:window.__TIDELAND.snapshot().player.stats.health}));pass('Inventory equips crafted clothing into its slot',worn.equipment?.body==='warmJacket');
  const protectedHit=await page.evaluate(()=>{const a=window.__TIDELAND,before=a.snapshot().player.stats.health,result=a.applyPlayerDamage({amount:10,type:'cold',sourceId:'equipment-qa'});return {before,after:a.snapshot().player.stats.health,result};});pass('Equipped jacket reduces cold damage at runtime',protectedHit.result.applied<10&&protectedHit.after===protectedHit.before-protectedHit.result.applied);
  await page.evaluate(()=>window.__TIDELAND.save());await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:150000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:150000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:180000});
  pass('Equipped clothing remains saved across reload',await page.evaluate(()=>window.__TIDELAND.snapshot().player.equipment?.body==='warmJacket'));
  pass('No browser application or WebGL console errors',errors.length===0);
  fs.writeFileSync(`${outputDir}/results.json`,JSON.stringify({checks,errors,actorId:selected.actor.id,initialSpecies:selected.actor.species,firstHit:first.health,death:killed.saved},null,2));await page.screenshot({path:`${outputDir}/post-hunt.png`});
}finally{await browser.close();}
