import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const out=process.env.TIDELAND_QA_DIR||'test-results/firearm';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN,args:['--enable-webgl','--use-gl=angle',`--use-angle=${process.env.TIDELAND_QA_ANGLE||'swiftshader'}`]});
const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const pass=(label,ok)=>{assert.ok(ok,label);console.log('PASS',label)};
try{
  await page.goto(process.env.TIDELAND_QA_URL||'http://127.0.0.1:5174',{waitUntil:'commit',timeout:30000});await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:300000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:300000});await page.locator('[data-action="new"]').click();await page.locator('[data-save-action="new"][data-save-slot="1"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:300000});await page.mouse.click(640,360);
  const encounter=await page.evaluate(()=>{const a=window.__TIDELAND,g=a.sim(),actor=a.wildlife().find(x=>x.species==='islandScavenger');if(!actor)throw Error('No scavenger generated for ranged QA');a.setCapturePaused(true);a.dev('god');g.state.inventory[2]={itemId:'salvageRevolver',count:1,condition:120,loadedAmmo:6};g.state.inventory[3]={itemId:'pistolAmmo',count:12};const x=actor.position.x,z=actor.position.z+2.5;a.teleport({x,y:a.height(x,z)+.06,z});a.lookAt({x:actor.position.x,y:actor.position.y+.95,z:actor.position.z});return {id:actor.id,health:actor.health};});await page.evaluate(()=>window.__TIDELAND.selectSlot(2));
  await page.waitForFunction(()=>window.__TIDELAND.cameraState().viewmodel.active==='salvageRevolver',null,{timeout:5000});pass('Quick slot equips the procedural salvage revolver viewmodel',true);
  await page.waitForTimeout(700);const before=await page.evaluate(id=>window.__TIDELAND.wildlife().find(x=>x.id===id).health,encounter.id);await page.mouse.click(640,360);await page.waitForTimeout(100);
  const fired=await page.evaluate(id=>{const a=window.__TIDELAND,s=a.snapshot(),target=a.wildlife().find(x=>x.id===id);return {health:target.health,loaded:s.inventory[2].loadedAmmo,condition:s.inventory[2].condition,reserve:s.inventory[3].count,alerted:target.alerted,awareness:target.awareness,screen:a.getScreen()};},encounter.id);
  pass('Visible first-person revolver fires a hitscan shot at the aimed scavenger',fired.health<before&&fired.loaded===5);pass('Firing wears the weapon and leaves reserve ammunition intact',fired.condition===119&&fired.reserve===12);
  pass('A loud firearm shot alerts its nearby human target',fired.alerted&&fired.awareness===1);
  await page.evaluate(()=>window.__TIDELAND.setCapturePaused(false));await page.keyboard.press('r');await page.waitForTimeout(220);const reloadPose=await page.evaluate(()=>window.__TIDELAND.cameraState().viewmodel.reloadProgress);pass('Reload produces a visible, smoothly animated revolver pose',reloadPose>.05&&reloadPose<1);await page.waitForFunction(()=>window.__TIDELAND.firearm().loaded===6,null,{timeout:10000});
  const reloaded=await page.evaluate(()=>window.__TIDELAND.firearm());pass('R reloads one round from reserve after the reload duration',reloaded.loaded===6&&reloaded.reserve===11&&!reloaded.reloading);
  await page.screenshot({path:`${out}/firearm-equipped.png`});await page.evaluate(()=>window.__TIDELAND.save());await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:300000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:300000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:300000});await page.waitForTimeout(350);
  const restored=await page.evaluate(id=>({weapon:window.__TIDELAND.snapshot().inventory[2],ammo:window.__TIDELAND.snapshot().inventory[3],actor:window.__TIDELAND.wildlife().find(x=>x.id===id)}),encounter.id);
  pass('Magazine, condition, reserve and wounded target survive save/reload',restored.weapon.loadedAmmo===6&&restored.weapon.condition===119&&restored.ammo.count===11&&restored.actor.health===fired.health);pass('Reload restores the same weapon viewmodel',await page.evaluate(()=>window.__TIDELAND.cameraState().viewmodel.active==='salvageRevolver'));pass('No application or WebGL console errors',errors.length===0);
  await page.screenshot({path:`${out}/firearm.png`});fs.writeFileSync(`${out}/results.json`,JSON.stringify({passed:true,encounter,before,fired,reloaded,restored,errors},null,2));
}finally{await browser.close()}
