import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const outputDir=process.env.TIDELAND_QA_DIR||'test-results/scavenger';fs.mkdirSync(outputDir,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN,args:['--enable-webgl','--use-gl=angle',`--use-angle=${process.env.TIDELAND_QA_ANGLE||'swiftshader'}`]});
const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
const pass=(label,value)=>{assert.ok(value,label);console.log('PASS',label);};
try{
  await page.goto(process.env.TIDELAND_QA_URL||'http://127.0.0.1:5174',{waitUntil:'commit',timeout:30000});await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:300000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:300000});
  await page.locator('[data-action="new"]').click();await page.locator('[data-save-action="new"][data-save-slot="1"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:300000});await page.mouse.click(640,360);
  const poiCoverage=await page.evaluate(()=>{const a=window.__TIDELAND,pois=a.world().pois.filter(p=>p.kind===1||p.kind===2),caches=a.snapshot().progression.stations.filter(s=>s.kind==='secureCache'),guards=a.wildlife().filter(x=>x.species==='islandScavenger');return {sites:pois.map(p=>({id:p.id,cache:caches.some(s=>s.id===`secure-cache-${p.id}`),guard:guards.some(g=>Math.hypot(g.position.x-p.position.x,g.position.z-p.position.z)<12)})),archetypes:guards.map(g=>g.archetype)};});pass('Relay and quarry are both guarded high-value POIs',poiCoverage.sites.length===2&&poiCoverage.sites.every(p=>p.cache&&p.guard));pass('POIs have deterministic melee, bow lookout and firearm guard roles',poiCoverage.archetypes.includes('scavenger')&&poiCoverage.archetypes.includes('lookout')&&poiCoverage.archetypes.includes('guard'));
  const target=await page.evaluate(()=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.species==='islandScavenger');if(!actor)throw Error('No seeded industrial scavenger spawned');a.setCapturePaused(true);const g=a.sim(),x=actor.position.x-1.25,z=actor.position.z;g.state.inventory[0]={itemId:'hatchet',count:1,condition:100};g.selectSlot(0);a.teleport({x,y:a.height(x,z)+.06,z});a.lookAt({x:actor.position.x,y:actor.position.y+.95,z:actor.position.z});return {id:actor.id,health:actor.health};});
  pass('A deterministic human scavenger spawns at an industrial POI',Boolean(target.id));
  const stealth=await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id),forwardX=Math.sin(actor.yaw),forwardZ=Math.cos(actor.yaw);let position=null;for(let step=0;step<48&&!position;step++){const angle=step*Math.PI*2/48,x=actor.position.x+Math.cos(angle)*3.5,z=actor.position.z+Math.sin(angle)*3.5,dx=x-actor.position.x,dz=z-actor.position.z;if((dx*forwardX+dz*forwardZ)/3.5>-.45)continue;const y=a.height(x,z);a.teleport({x,y:y+.06,z});if(a.scavengerLineOfSightForTest(id))position={x,y:y+.06,z};}if(!position)throw Error('Could not find a clear behind-the-guard stealth position');a.configureWildlifeForTest(id,{wanderX:actor.position.x,wanderZ:actor.position.z,wanderTime:-100,awareness:0,alerted:false,angered:false,canSeePlayer:false,perceptionCooldown:0,state:'wander'});return position;},target.id);pass('Stealth approach setup is active in clear terrain',Boolean(stealth));
  await page.waitForTimeout(1100);await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:30000});const undetected=await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id);a.setCapturePaused(true);return actor.awareness<.1&&!actor.alerted&&actor.state!=='attack';},target.id);pass('Scavenger does not detect a nearby player behind its view cone',undetected);
  await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id),player=a.snapshot().player.position;a.configureWildlifeForTest(id,{yaw:Math.atan2(player.x-actor.position.x,player.z-actor.position.z),perceptionCooldown:0,wanderX:actor.position.x,wanderZ:actor.position.z,wanderTime:-100});a.setCapturePaused(false);},target.id);
  await page.waitForFunction(id=>{const actor=window.__TIDELAND.wildlife().find(x=>x.id===id);return actor?.awareness>.2;},target.id,{timeout:30000});const suspicion=await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id);a.setCapturePaused(true);return {awareness:actor.awareness,alerted:actor.alerted};},target.id);pass('Scavenger builds suspicion while the visible player approaches',suspicion.awareness>.2&&!suspicion.alerted);await page.evaluate(id=>{const a=window.__TIDELAND;a.configureWildlifeForTest(id,{awareness:.99,alerted:false,perceptionCooldown:0});a.setCapturePaused(false);},target.id);await page.waitForFunction(id=>window.__TIDELAND.wildlife().find(x=>x.id===id)?.alerted===true,target.id,{timeout:15000});await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id);a.setCapturePaused(true);const x=actor.position.x-1.25,z=actor.position.z;a.teleport({x,y:a.height(x,z)+.06,z});a.lookAt({x:actor.position.x,y:actor.position.y+.95,z:actor.position.z});},target.id);pass('Suspicion threshold raises a scavenger alarm',await page.evaluate(id=>window.__TIDELAND.wildlife().find(x=>x.id===id)?.awareness===1,target.id));
  const pressure=await page.evaluate(id=>{const a=window.__TIDELAND;a.provokeWildlife(id);a.setCapturePaused(false);return a.snapshot().player.stats.health;},target.id);await page.waitForFunction(h=>window.__TIDELAND.snapshot().player.stats.health<h,pressure,{timeout:15000});
  await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));pass('Scavenger attacks through the existing damage system',await page.evaluate(h=>window.__TIDELAND.snapshot().player.stats.health<h,pressure));
  for(let hit=0;hit<12;hit++){const state=await page.evaluate(id=>{const a=window.__TIDELAND;return {health:a.wildlife().find(x=>x.id===id)?.health,state:a.wildlife().find(x=>x.id===id)?.state};},target.id);if(state.state==='dead')break;await page.evaluate(id=>window.__TIDELAND.strikeWildlife(id),target.id);await page.waitForTimeout(550);}
  const loot=await page.evaluate(id=>{const a=window.__TIDELAND,g=a.sim(),actor=a.wildlife().find(x=>x.id===id),s=g.state;return {dead:actor?.state==='dead',saved:s.nodeChanges[id],items:s.inventory.filter(Boolean).map(x=>x.itemId),drops:s.drops.map(x=>x.stack.itemId),notice:document.querySelector('.notifications')?.textContent??''};},target.id);
  pass('Defeated scavenger rewards salvage, relay access card and records death',loot.dead&&loot.saved===0&&(loot.items.includes('scrap')||loot.drops.includes('scrap'))&&(loot.items.includes('wiring')||loot.drops.includes('wiring'))&&(loot.items.includes('relayAccessCard')||loot.drops.includes('relayAccessCard')));
  const sealed=await page.evaluate(()=>{const a=window.__TIDELAND,s=a.snapshot().progression.stations.find(x=>x.kind==='secureCache'&&x.locked);if(!s)throw Error('No secured Gen5 POI cache generated');a.teleport({x:s.position.x,y:s.position.y+.1,z:s.position.z+2.5});a.lookAt({x:s.position.x,y:s.position.y+.4,z:s.position.z});return {id:s.id,position:s.position};});await page.waitForFunction(()=>window.__TIDELAND.interaction()?.action==='UNLOCK',null,{timeout:12000});pass('High-value sealed cache requires the scavenger access card',true);await page.keyboard.press('e');await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='station',null,{timeout:10000});pass('Access card unlocks and opens the cache',await page.evaluate(id=>{const a=window.__TIDELAND,s=a.snapshot().progression.stations.find(x=>x.id===id);return s?.locked===false&&!s.inventory.every(x=>!x)&&!a.snapshot().inventory.some(x=>x?.itemId==='relayAccessCard');},sealed.id));await page.screenshot({path:`${outputDir}/secure-cache-open.png`});
  await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:300000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:300000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:300000});
  pass('Defeated scavenger and unlocked cache persist after save and reload',await page.evaluate(ids=>!window.__TIDELAND.wildlife().some(x=>x.id===ids.actor)&&window.__TIDELAND.snapshot().progression.stations.find(x=>x.id===ids.cache)?.locked===false,{actor:target.id,cache:sealed.id}));
  const lookout=await page.evaluate(()=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.archetype==='lookout');if(!actor)throw Error('No deterministic lookout generated');let player=null;for(let step=0;step<48&&!player;step++){const angle=step*Math.PI*2/48,x=actor.position.x+Math.cos(angle)*15,z=actor.position.z+Math.sin(angle)*15,y=a.height(x,z)+.06;a.teleport({x,y,z});a.lookAt({x:actor.position.x,y:actor.position.y+1,z:actor.position.z});if(a.scavengerLineOfSightForTest(actor.id))player={x,y,z};}if(!player)throw Error('Could not find a clear ranged lookout lane');const p=a.snapshot().player.position;a.configureWildlifeForTest(actor.id,{yaw:Math.atan2(p.x-actor.position.x,p.z-actor.position.z),alerted:true,awareness:1,canSeePlayer:false,memorySeconds:0,attackCooldown:0,perceptionCooldown:0});a.setCapturePaused(false);return {id:actor.id,health:a.snapshot().player.stats.health,player};});
  await page.waitForFunction(h=>window.__TIDELAND.snapshot().player.stats.health<h,lookout.health,{timeout:15000});const ranged=await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id);a.setCapturePaused(true);return {health:a.snapshot().player.stats.health,actor:actor&&{archetype:actor.archetype,state:actor.state,canSeePlayer:actor.canSeePlayer}};},lookout.id);pass('Ranged lookout lands a typed projectile hit with line of sight',ranged.health<lookout.health&&ranged.actor?.archetype==='lookout'&&ranged.actor.state==='attack'&&ranged.actor.canSeePlayer);await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id),x=actor.position.x,z=actor.position.z+3,y=a.height(x,z)+.06;a.selectSlot(4);a.teleport({x,y,z});a.lookAt({x:actor.position.x,y:actor.position.y+.85,z:actor.position.z});const p=a.snapshot().player.position;a.configureWildlifeForTest(id,{yaw:Math.atan2(p.x-actor.position.x,p.z-actor.position.z)});a.setCapturePaused(false);},lookout.id);await page.waitForTimeout(250);await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));await page.screenshot({path:`${outputDir}/lookout-ranged.png`});
  const firearmGuard=await page.evaluate(()=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.archetype==='guard');if(!actor)throw Error('No seeded industrial firearm guard');let position=null;for(let step=0;step<48&&!position;step++){const angle=step*Math.PI*2/48,x=actor.position.x+Math.cos(angle)*18,z=actor.position.z+Math.sin(angle)*18,y=a.height(x,z)+.06;a.teleport({x,y,z});a.lookAt({x:actor.position.x,y:actor.position.y+1,z:actor.position.z});if(a.scavengerLineOfSightForTest(actor.id))position={x,y,z};}if(!position)throw Error('No clear firearm guard lane');const p=a.snapshot().player.position;a.configureWildlifeForTest(actor.id,{yaw:Math.atan2(p.x-actor.position.x,p.z-actor.position.z),alerted:true,awareness:1,attackCooldown:0,perceptionCooldown:0,memorySeconds:0});a.setCapturePaused(false);return {id:actor.id,health:a.snapshot().player.stats.health};});await page.waitForFunction(h=>window.__TIDELAND.snapshot().player.stats.health<h,firearmGuard.health,{timeout:15000});const gunfire=await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id);a.setCapturePaused(true);return {health:a.snapshot().player.stats.health,actor:actor&&{archetype:actor.archetype,state:actor.state,canSeePlayer:actor.canSeePlayer}};},firearmGuard.id);pass('Armored POI guard lands a typed firearm projectile only across clear LOS',gunfire.health<firearmGuard.health&&gunfire.actor?.archetype==='guard'&&gunfire.actor.state==='attack'&&gunfire.actor.canSeePlayer);await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id),x=actor.position.x,z=actor.position.z+4,y=a.height(x,z)+.06;a.selectSlot(4);a.teleport({x,y,z});a.lookAt({x:actor.position.x,y:actor.position.y+.85,z:actor.position.z});const p=a.snapshot().player.position;a.configureWildlifeForTest(id,{yaw:Math.atan2(p.x-actor.position.x,p.z-actor.position.z)});a.setCapturePaused(false);},firearmGuard.id);await page.waitForTimeout(250);await page.evaluate(()=>window.__TIDELAND.setCapturePaused(true));await page.screenshot({path:`${outputDir}/firearm-guard.png`});
  await page.evaluate(id=>{const a=window.__TIDELAND,actor=a.wildlife().find(x=>x.id===id),x=actor.position.x-1.25,z=actor.position.z,y=a.height(x,z)+.06;a.teleport({x,y,z});a.selectSlot(0);a.lookAt({x:actor.position.x,y:actor.position.y+.68,z:actor.position.z});},firearmGuard.id);for(let hit=0;hit<14;hit++){if(await page.evaluate(id=>window.__TIDELAND.wildlife().find(x=>x.id===id)?.state==='dead',firearmGuard.id))break;await page.evaluate(id=>window.__TIDELAND.strikeWildlife(id),firearmGuard.id);await page.waitForTimeout(550);}const guardLoot=await page.evaluate(id=>{const a=window.__TIDELAND,g=a.sim(),actor=a.wildlife().find(x=>x.id===id),state=g.state;return {dead:actor?.state==='dead',saved:state.nodeChanges[id],machineParts:state.inventory.some(x=>x?.itemId==='machineParts')||state.drops.some(x=>x.stack.itemId==='machineParts'),accessCards:state.inventory.filter(x=>x?.itemId==='relayAccessCard').reduce((n,x)=>n+(x?.count??0),0)};},firearmGuard.id);pass('Defeated guard rewards industrial machine parts and persists its death',guardLoot.dead&&guardLoot.saved===0&&guardLoot.machineParts);await page.reload();await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:300000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:300000});await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing',null,{timeout:300000});pass('Guard death and industrial loot survive save/reload',await page.evaluate(id=>!window.__TIDELAND.wildlife().some(x=>x.id===id)&&window.__TIDELAND.snapshot().inventory.some(x=>x?.itemId==='machineParts'),firearmGuard.id));pass('No browser application or WebGL errors',errors.length===0);
  fs.writeFileSync(`${outputDir}/results.json`,JSON.stringify({passed:true,target,loot,errors},null,2));await page.screenshot({path:`${outputDir}/scavenger.png`});
}finally{await browser.close();}
