import {chromium} from 'playwright-core';import fs from 'node:fs';import assert from 'node:assert/strict';
const dir='artifacts/survival-expansion',b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-gl=angle','--use-angle=metal']});const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const shot=async n=>{await p.waitForTimeout(350);await p.screenshot({path:`${dir}/${n}.png`})};const command=line=>p.evaluate(line=>window.__TIDELAND.command(line),line);
try{await p.goto('http://localhost:5173');await p.waitForFunction(()=>window.__TIDELAND);await p.getByRole('button',{name:'01 NEW GAME'}).click();await p.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing');await shot('spawn');
console.log('errors',errors);await command('give resources');await command('give buildkit');
const stations=await p.evaluate(()=>{const a=window.__TIDELAND;return ['storage','storage','furnace','workbench1','workbench2','workbench3','campfire','bedroll'].map((k,i)=>a.stationPlace(k,{x:40+(i%4)*3,y:a.height(40+(i%4)*3,220+Math.floor(i/4)*4),z:220+Math.floor(i/4)*4}));});assert(stations.every(Boolean));checks.push('Distinct station placement');
const aim=async s=>{await p.evaluate(s=>{const a=window.__TIDELAND;a.teleport({x:s.position.x,y:s.position.y+.2,z:s.position.z+2});a.lookAt({x:s.position.x,y:s.position.y+.45,z:s.position.z})},s);await p.waitForTimeout(500);};
await aim(stations[0]);await shot('storage');await p.keyboard.press('KeyE');await p.waitForTimeout(200);assert(await p.locator('.survival-panel:not([hidden])').count()>0);await shot('open-storage');
const wood=await p.evaluate(()=>window.__TIDELAND.snapshot().inventory.findIndex(x=>x?.itemId==='wood'));await p.locator(`.station-slot[data-container="player"][data-slot="${wood}"]`).dragTo(p.locator('.station-slot[data-container="station"][data-slot="0"]'));await p.waitForTimeout(250);assert.equal(await p.evaluate(id=>window.__TIDELAND.snapshot().progression.stations.find(s=>s.id===id).inventory[0]?.itemId,stations[0].id),'wood');checks.push('DOM storage drag transfer');await p.keyboard.press('Escape');
await p.evaluate(ids=>{const s=window.__TIDELAND.sim().state.progression.stations;const f=s.find(s=>s.id===ids[2]);f.inventory[0]={itemId:'ore',count:20};f.inventory[2]={itemId:'wood',count:10};const fire=s.find(s=>s.id===ids[6]);fire.inventory[0]={itemId:'wood',count:5};fire.active=true;},stations.map(s=>s.id));await aim(stations[2]);await shot('furnace-inactive');await p.keyboard.press('KeyE');await p.getByRole('button',{name:'TURN ON',exact:true}).click();await shot('furnace-ui');await p.keyboard.press('Escape');await shot('furnace-active');
for(const [i,name]of [[3,'workbench1'],[5,'workbench3'],[6,'campfire'],[7,'bedroll']]){await aim(stations[i]);await shot(name);}await p.keyboard.press('KeyE');await p.getByRole('button',{name:'SET RESPAWN POINT',exact:true}).click();await p.keyboard.press('Escape');
const before=await p.evaluate(()=>{const a=window.__TIDELAND;a.save();return a.snapshot()});assert(before.progression.spawnId);await p.reload();await p.waitForFunction(()=>window.__TIDELAND);await p.getByRole('button',{name:/02 CONTINUE/}).click();await p.waitForFunction(()=>window.__TIDELAND.getScreen()==='playing');const after=await p.evaluate(()=>window.__TIDELAND.snapshot());assert.equal(after.progression.stations.length,before.progression.stations.length);assert.deepEqual(after.progression.stations.find(s=>s.id===stations[0].id).inventory,before.progression.stations.find(s=>s.id===stations[0].id).inventory);assert.equal(after.progression.stations.find(s=>s.id===stations[1].id).inventory[0],null);assert.equal(after.progression.spawnId,before.progression.spawnId);checks.push('Independent storage and spawn point restored');
for(const weather of ['rain','fog','storm']){await command(`weather ${weather}`);await p.waitForTimeout(6500);await shot(weather);}await command('weather clear');await command('teleport poi-0');await p.waitForTimeout(1000);await shot('poi');await p.keyboard.press('KeyM');await shot('map');await p.locator('.world-map canvas').click({position:{x:220,y:200}});await p.keyboard.press('KeyM');checks.push('Map waypoint input');
await command('save');assert.deepEqual(errors,[]);fs.writeFileSync(`${dir}/results.json`,JSON.stringify({checks,errors,stations:stations.length,stats:await p.evaluate(()=>window.__TIDELAND.stats())},null,2));console.log({checks,errors});}finally{await b.close()}
