import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const out=process.env.TIDELAND_QA_DIR||'test-results/world-art',base=process.env.TIDELAND_QA_URL||'http://127.0.0.1:5173';fs.mkdirSync(out,{recursive:true});
const fixture=JSON.parse(fs.readFileSync(`${out}/v090-save.json`,'utf8'));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN,args:['--enable-webgl','--use-gl=angle',`--use-angle=${process.env.TIDELAND_QA_ANGLE||'swiftshader'}`]});
let page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const pass=(name,ok)=>{assert.ok(ok,name);results.push(name);console.log('PASS',name)};
const boot=async()=>{await page.waitForFunction(()=>window.__TIDELAND,null,{timeout:180000});await page.locator('.loading-screen').waitFor({state:'hidden',timeout:180000});await page.waitForFunction(()=>window.__TIDELAND?.getScreen()==='menu'&&document.querySelector('.loading-screen')?.hidden===true,null,{timeout:180000})};
const play=async()=>{await page.locator('[data-action="continue"]').click();await page.waitForFunction(()=>window.__TIDELAND?.getScreen()==='playing',null,{timeout:180000})};
const shot=async(name,p,target)=>{await page.evaluate(({p,target})=>{const a=window.__TIDELAND;a.teleport(p);a.lookAt(target||{x:p.x+45,y:p.y+3,z:p.z-40});},{p,target});await page.waitForTimeout(600);await page.screenshot({path:`${out}/${name}.png`,timeout:60000})};
try{
 // Capture a real v0.9.1 revision-2 save from its immutable archive, including
 // depleted nodes and a placed structure, then load it through current code.
 const archive=await browser.newPage({viewport:{width:1280,height:720}}),archiveErrors=[];archive.on('pageerror',e=>archiveErrors.push(e.message));
 await archive.goto('https://rsvora-bit.github.io/RUST---clon/versions/v0.9.1/');await archive.waitForFunction(()=>!!window.__TIDELAND,null,{timeout:180000});await archive.locator('.loading-screen').waitFor({state:'hidden',timeout:180000});
 await archive.locator('#world-seed').fill('731942');await archive.locator('[data-action="new"]').click();await archive.locator('[data-save-action="new"][data-save-slot="1"]').click();await archive.waitForFunction(()=>window.__TIDELAND?.getScreen()==='playing',null,{timeout:180000});
 const revision2=await archive.evaluate(()=>{const a=window.__TIDELAND,g=a.sim(),p=a.world().spawn;a.setCapturePaused(true);a.dev('resources');g.addItem('scrap',37);g.state.nodeChanges['tree-4']=123;g.state.player.position={x:p.x+2,y:a.height(p.x+2,p.z)+.2,z:p.z+2};a.teleport(g.state.player.position);const built=a.placeAt('foundation',{x:p.x+5,y:a.height(p.x+5,p.z+5),z:p.z+5}).structure;const station=a.stationPlace('bedroll',{x:p.x+8,y:a.height(p.x+8,p.z+8),z:p.z+8});g.state.progression.tech.unlocked.push('efficiencyTooling');g.state.progression.waypoint={x:100,z:-100};a.save();const prefix='tideland-archive:v0.9.1:';return {state:a.snapshot(),nodes:a.nodes(),world:a.world(),built,station,storage:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith(prefix)).map(k=>[k.slice(prefix.length),localStorage.getItem(k.slice(prefix.length))]))};});
 assert.equal(archiveErrors.length,0,archiveErrors.join('\n'));assert.equal(revision2.state.worldRevision,2);assert.ok(revision2.built&&revision2.station);
 fs.writeFileSync(`${out}/v091-save.json`,JSON.stringify(revision2));await archive.close();
 await page.goto(base);await boot();await page.evaluate(storage=>{localStorage.clear();for(const [key,value] of Object.entries(storage))localStorage.setItem(key,value)},revision2.storage);await page.reload();await boot();await play();
 const restored2=await page.evaluate(()=>({state:window.__TIDELAND.snapshot(),world:window.__TIDELAND.world(),nodes:window.__TIDELAND.nodes()}));
 pass('Real archived v0.9.1 revision-2 save retains its revision',restored2.state.worldRevision===2&&restored2.world.revision===2);
 pass('Revision-2 tree and resource identities stay exact',JSON.stringify(restored2.nodes.map(n=>({id:n.id,kind:n.kind,position:n.position})))===JSON.stringify(revision2.nodes.map(n=>({id:n.id,kind:n.kind,position:n.position}))));
 pass('Revision-2 POIs and routes stay exact',JSON.stringify(restored2.world.pois)===JSON.stringify(revision2.world.pois)&&JSON.stringify(restored2.world.trails)===JSON.stringify(revision2.world.trails));
 for(const key of ['inventory','structures','nodeChanges','drops','craftQueue'])pass(`Revision-2 ${key} retained`,JSON.stringify(restored2.state[key])===JSON.stringify(revision2.state[key]));
 pass('Revision-2 stations and research retained',JSON.stringify(restored2.state.progression.stations)===JSON.stringify(revision2.state.progression.stations)&&JSON.stringify(restored2.state.progression.tech)===JSON.stringify(revision2.state.progression.tech));
 pass('Revision-2 player position retained',Math.hypot(restored2.state.player.position.x-revision2.state.player.position.x,restored2.state.player.position.z-revision2.state.player.position.z)<.05);
 pass('Revision-2 building collider restored',await page.evaluate(id=>window.__TIDELAND.hasStructureCollider(id),revision2.built.id));
 await page.close();page=await browser.newPage({viewport:{width:1280,height:720}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto(base);await boot();
 await page.evaluate(storage=>{localStorage.clear();for(const [key,value] of Object.entries(storage))localStorage.setItem(key.replace('tideland-archive:v0.9.0:',''),value);},fixture.storage);await page.reload();await boot();await play();
 const restored=await page.evaluate(()=>{const a=window.__TIDELAND;a.setCapturePaused(true);return {state:a.snapshot(),world:a.world(),nodes:a.nodes()}});
 pass('Real archived v0.9.0 gen5 save loads with revision 1',restored.state.worldGeneration===5&&restored.world.revision===1&&restored.state.worldRevision===undefined);
 pass('All archived resource IDs and positions remain identical',JSON.stringify(restored.nodes)===JSON.stringify(fixture.nodes));
 pass('Archived POIs and roads remain identical',JSON.stringify(restored.world.pois)===JSON.stringify(fixture.world.pois)&&JSON.stringify(restored.world.trails)===JSON.stringify(fixture.world.trails));
 for(const key of ['inventory','structures','nodeChanges','drops','craftQueue'])pass(`Archived ${key} retained`,JSON.stringify(restored.state[key])===JSON.stringify(fixture.state[key]));
 pass('Archived stations and Tech Tree retained',JSON.stringify(restored.state.progression.stations)===JSON.stringify(fixture.state.progression.stations)&&JSON.stringify(restored.state.progression.tech)===JSON.stringify(fixture.state.progression.tech));
 pass('Archived player position not reset',Math.hypot(restored.state.player.position.x-fixture.state.player.position.x,restored.state.player.position.z-fixture.state.player.position.z)<.05);
 pass('Archived building has collider after load',await page.evaluate(id=>window.__TIDELAND.hasStructureCollider(id),fixture.built.id));
 await shot('legacy-v090-save',restored.world.spawn);
 // New revision is explicit, never assigned on loading an old snapshot.
 await page.close();page=await browser.newPage({viewport:{width:1280,height:720}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(base);await boot();await page.locator('#world-seed').fill('731942');await page.locator('[data-action="new"]').click();await page.locator('.save-browser:not([hidden])').waitFor({state:'visible',timeout:30000});await page.locator('[data-save-action="new"][data-save-slot="1"]').click();await page.waitForFunction(()=>window.__TIDELAND?.getScreen()==='playing',null,{timeout:180000});
 const world=await page.evaluate(()=>{const a=window.__TIDELAND;a.setCapturePaused(true);a.dev('god');a.dev('fly');a.dev('time',10);return a.world()});
 pass('New world uses revision-6 scale and saved identity',world.revision===6&&(await page.evaluate(()=>window.__TIDELAND.snapshot().worldRevision))===6&&world.size===1664);const stormwatch=world.pois.find(p=>p.kind===4),wreck=world.pois.find(p=>p.kind===5),pier=world.pois.find(p=>p.kind===6),relay=world.pois.find(p=>p.kind===7);pass('Revision 6 preserves old sites and adds coastal/highland landmarks',world.pois.length===8&&stormwatch?.name==='Stormwatch Station'&&wreck?.name==='Breakwater Cargo Wreck'&&pier?.name==='Tidal Survey Pier'&&relay?.name==='Highland Relay'&&world.trails.length===8);if(stormwatch)await shot('stormwatch-station',{x:stormwatch.position.x+10,y:stormwatch.position.y+.15,z:stormwatch.position.z+6},{x:stormwatch.position.x,y:stormwatch.position.y+2.3,z:stormwatch.position.z});if(wreck)await shot('breakwater-wreck',{x:wreck.position.x+10,y:wreck.position.y+5,z:wreck.position.z+9},{x:wreck.position.x,y:wreck.position.y+1.2,z:wreck.position.z});if(pier)await shot('tidal-survey-pier',{x:pier.position.x+9,y:pier.position.y+4,z:pier.position.z+11},{x:pier.position.x,y:pier.position.y+3,z:pier.position.z});if(relay)await shot('highland-relay',{x:relay.position.x+17,y:relay.position.y+14,z:relay.position.z+19},{x:relay.position.x,y:relay.position.y+6,z:relay.position.z});
 const containers=await page.evaluate(()=>{const state=window.__TIDELAND.snapshot(),loot=state.progression.stations.find(s=>s.id==='loot-poi-4'),cache=state.progression.stations.find(s=>s.id==='secure-cache-poi-4');return {loot:loot&&{id:loot.id,items:loot.inventory.filter(Boolean).length},cache:cache&&{id:cache.id,locked:cache.locked,items:cache.inventory.filter(Boolean).length}}});pass('Stormwatch saves a loot crate and locked cache with loot',containers.loot?.items>0&&containers.cache?.locked&&containers.cache.items>0);await page.evaluate(id=>{const a=window.__TIDELAND;a.sim().state.inventory=Array(30).fill(null);a.stationOpen(id);},containers.loot.id);await page.locator('[data-action="take"]').click();await page.waitForFunction(()=>!window.__TIDELAND.snapshot().progression.stations.some(s=>s.id==='loot-poi-4'));await page.waitForTimeout(800);pass('Stormwatch container empties through the ordinary loot UI and collapse lifecycle',await page.evaluate(()=>!window.__TIDELAND.snapshot().progression.stations.some(s=>s.id==='loot-poi-4')));const wreckLoot=await page.evaluate(()=>{const stations=window.__TIDELAND.snapshot().progression.stations,loot=stations.find(s=>s.id==='loot-poi-5'),cache=stations.find(s=>s.id==='secure-cache-poi-5');return {loot:loot?.inventory.filter(Boolean).map(x=>x.itemId),cache:cache&&{locked:cache.locked,items:cache.inventory.filter(Boolean).map(x=>x.itemId)}}});pass('Breakwater has salvage identity and a locked cargo cache',wreckLoot.loot?.some(id=>['machineParts','shotgunShells','cookedMeat'].includes(id))&&wreckLoot.cache?.locked&&wreckLoot.cache.items.includes('machineParts')&&wreckLoot.cache.items.includes('shotgunShells'));
 const art=await page.evaluate(()=>window.__TIDELAND.worldArt());pass('Three cheap nonphysical irregular mountain layers exist',art.horizonLayers===3&&art.horizonTriangles===5184);pass('Revision 6 increases instanced grass cover',art.grassInstances>=84000);pass('Revision 6 batches grass through shared instanced chunks',art.grassChunks>0);pass('Distance culling compacts only nearby tree instances',art.renderedTrees>0&&art.renderedTrees<art.trees.length&&art.renderedTrees===art.renderedTreeInstances&&art.trees.length===1500);
 const palms=art.trees.filter(t=>t.species===5);pass('Palm canopies have climate-correct placement',palms.length>0&&palms.every(t=>t.climate.temperature>.53&&t.position.y<26));
 const roads=world.trails.flat();pass('No routed road sample is deep underwater',await page.evaluate(points=>points.every(p=>window.__TIDELAND.height(p.x,p.z)>=1.15),roads));
 pass('Trees leave road corridor clear',art.trees.every(t=>roads.every(p=>Math.hypot(t.position.x-p.x,t.position.z-p.z)>4.4)));
 const road=world.trails[0],mid=Math.floor(road.length*.45);await shot('road-new',road[mid],{...road[Math.min(road.length-1,mid+15)],y:road[Math.min(road.length-1,mid+15)].y+1});
 await shot('spawn-understory',world.spawn,{x:world.spawn.x+40,y:world.spawn.y+1,z:world.spawn.z-50});
 await shot('palm-warm-coast',{x:palms[0].position.x+7,y:palms[0].position.y+1,z:palms[0].position.z+8},{...palms[0].position,y:palms[0].position.y+6});
 const views=await page.evaluate(()=>{const a=window.__TIDELAND,out={};for(let z=-820;z<=820;z+=20)for(let x=-820;x<=820;x+=20){const h=a.height(x,z),b=a.biome(x,z);if(h>3&&!out[b])out[b]={x,y:h+3,z};}return out});const shore=await page.evaluate(()=>{const a=window.__TIDELAND;for(let z=-816;z<=816;z+=6)for(let x=-816;x<=816;x+=6){const y=a.height(x,z);if(y<1.35||y>2.35)continue;for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]])if(a.height(x+dx*6,z+dz*6)<.45)return{x,y,z,waterX:dx,waterZ:dz};}return null;});pass('Revision 6 has a distinct wetland climate band with instanced reeds',!!views['WETLAND / MARSH']&&art.reedInstances>0);pass('Revision 6 coast has substantial batched pebble, driftwood and seaweed cover',art.shoreInstances['Tide-washed pebbles']>=600&&art.shoreInstances['Stranded branches']>=70&&art.shoreInstances['Tidal seaweed']>=75);console.log('SHORE INSTANCES',art.shoreInstances);const shoreCells=new Map();for(const [kind,points] of Object.entries(art.shoreLocations))for(const p of points){const key=`${Math.floor(p.x/32)},${Math.floor(p.z/32)}`,cell=shoreCells.get(key)||{x:0,y:0,z:0,count:0,kinds:new Set()};cell.x+=p.x;cell.y+=p.y;cell.z+=p.z;cell.count++;cell.kinds.add(kind);shoreCells.set(key,cell);}const shoreCluster=[...shoreCells.values()].sort((a,b)=>b.count-a.count)[0];if(shoreCluster){const target={x:shoreCluster.x/shoreCluster.count,y:shoreCluster.y/shoreCluster.count,z:shoreCluster.z/shoreCluster.count},waterDirection=await page.evaluate(p=>{const a=window.__TIDELAND;return [[1,0],[-1,0],[0,1],[0,-1]].sort((u,v)=>a.height(p.x+u[0]*6,p.z+u[1]*6)-a.height(p.x+v[0]*6,p.z+v[1]*6))[0]},target);await shot('shoreline-detail',{x:target.x-waterDirection[0]*9,y:target.y+4,z:target.z-waterDirection[1]*9},{x:target.x+waterDirection[0]*10,y:target.y+.1,z:target.z+waterDirection[1]*10});}const reedCells=new Map();for(const p of art.reedLocations){const key=`${Math.floor(p.x/28)},${Math.floor(p.z/28)}`,cell=reedCells.get(key)||{x:0,y:0,z:0,count:0};cell.x+=p.x;cell.y+=p.y;cell.z+=p.z;cell.count++;reedCells.set(key,cell);}const reedCluster=[...reedCells.values()].sort((a,b)=>b.count-a.count)[0];if(reedCluster){const target={x:reedCluster.x/reedCluster.count,y:reedCluster.y/reedCluster.count,z:reedCluster.z/reedCluster.count};pass('Wetland reed instances form visible clustered stands',reedCluster.count>=4);await shot('wetland-reed-stand',{x:target.x+18,y:target.y+6,z:target.z+18},{x:target.x,y:target.y+1.2,z:target.z});await shot('wetland-reed-close',{x:target.x+4,y:target.y+2,z:target.z+4},{x:target.x,y:target.y+1.1,z:target.z});}
 const denseForest=await page.evaluate(()=>{const a=window.__TIDELAND,trees=a.worldArt().trees.filter(t=>a.biome(t.position.x,t.position.z)==='TEMPERATE FOREST');let best={count:0,position:trees[0]?.position};for(const tree of trees){let count=0;for(const other of trees)if(Math.hypot(tree.position.x-other.position.x,tree.position.z-other.position.z)<58)count++;if(count>best.count)best={count,position:tree.position};}return best;});
 if(denseForest.position){await shot('dense-forest-cluster',{x:denseForest.position.x+112,y:denseForest.position.y+18,z:denseForest.position.z+96},{x:denseForest.position.x,y:denseForest.position.y+8,z:denseForest.position.z});const specimen=art.trees.find(t=>(t.species===1||t.species===4)&&Math.hypot(t.position.x-denseForest.position.x,t.position.z-denseForest.position.z)<58);if(specimen)await shot('forest-bark-detail',{x:specimen.position.x+8,y:specimen.position.y+4,z:specimen.position.z+8},{x:specimen.position.x,y:specimen.position.y+5,z:specimen.position.z});console.log('FOREST CLUSTER',denseForest.count,denseForest.position);}
 for(const biome of ['TEMPERATE FOREST','TEMPERATE GRASSLAND','WETLAND / MARSH','ARID','SNOW / ALPINE','ROCKY MOUNTAIN'])await shot(`biome-${biome.replaceAll(/[^A-Z]/g,'-')}`,views[biome]);
 for(const [name,hour,weather] of [['horizon-day',10,'clear'],['horizon-evening',18,'clear'],['horizon-night',0,'clear'],['horizon-storm',10,'storm']]){await page.evaluate(({hour,weather})=>{const a=window.__TIDELAND;a.dev('time',hour);const w=a.sim().state.progression.weather;Object.assign(w,{kind:weather,remaining:3600,blend:weather==='storm'?1:0,storm:weather==='storm'?1:0,rain:weather==='storm'?1:0,mist:0})},{hour,weather});await shot(name,{x:world.spawn.x,y:10,z:world.spawn.z},{x:world.spawn.x-150,y:20,z:world.spawn.z+130});}
 // Fast camera sweep uses the actual render loop and covers both sides of foliage.
 for(let i=0;i<16;i++){await page.evaluate(({p,i})=>window.__TIDELAND.lookAt({x:p.x+Math.cos(i/16*Math.PI*2)*80,y:p.y+6,z:p.z+Math.sin(i/16*Math.PI*2)*80}),{p:palms[0].position,i});await page.waitForTimeout(80)}
 pass('Camera sweep produces no WebGL/application errors',errors.length===0);
 await page.evaluate(()=>window.__TIDELAND.save());const stable=await page.evaluate(()=>window.__TIDELAND.world());await page.reload();await boot();await play();const reload=await page.evaluate(()=>window.__TIDELAND.world());pass('Revision 6 save/reload keeps roads, POIs and node count',JSON.stringify(stable)===JSON.stringify(reload));
 fs.writeFileSync(`${out}/world-art-results.json`,JSON.stringify({passed:true,results,errors,palms:palms.length},null,2));
}catch(e){fs.writeFileSync(`${out}/world-art-results.json`,JSON.stringify({passed:false,results,errors,error:e.message},null,2));throw e}finally{await browser.close()}
