import {ITEMS} from '../items/definitions';
import {itemName} from '../items/localization';
import type {ItemStack,Structure} from '../core/types';
import {currentRecyclerRecipe,HOMESTEAD_RADIUS,isStationOutputSlot,poweredHomesteadIds,poweredLampIds,STATIONS,stationStatus,type Station,type SlotRef} from './stations';
import './survival.css';

const stationNames:Record<Station['kind'],[string,string]>={storage:['STORAGE','ÚLOŽIŠTĚ'],furnace:['FURNACE','PEC'],workbench1:['WORKBENCH I','PRACOVNÍ STŮL I'],workbench2:['WORKBENCH II','PRACOVNÍ STŮL II'],workbench3:['WORKBENCH III','PRACOVNÍ STŮL III'],campfire:['CAMPFIRE','OHNIŠTĚ'],bedroll:['BEDROLL','SPACÍ VÁLEC'],loot:['SALVAGE','ZÁSOBA'],secureCache:['SECURE CACHE','ZABEZPEČENÁ SCHRÁNKA'],deathbag:['LOST PACK','ZTRACENÝ BATOH'],recycler:['RECYCLER','RECYKLÉR'],generator:['GENERATOR','GENERÁTOR'],powerSwitch:['POWER SWITCH','VYPÍNAČ'],lamp:['UTILITY LAMP','PRACOVNÍ SVÍTILNA'],homesteadCore:['HOMESTEAD BEACON','MAJETKOVÝ MAJÁK']};
const stationText=(cs:boolean,en:string,cz:string)=>cs?cz:en;

export class StationUI {
  readonly root=document.createElement('section');private station:Station|null=null;private drag:SlotRef|null=null;private split=false;private hash='';private powerCheckAt=0;private poweredLamps=new Set<string>();private poweredHomesteads=new Set<string>();private structures:Structure[]=[];
  constructor(parent:HTMLElement,private actions:{move:(id:string,a:SlotRef,b:SlotRef,split:boolean)=>void;takeAll:(id:string)=>void;toggle:(id:string)=>void;spawn:(id:string)=>void;openTechTree:(id:string)=>void;close:()=>void}){
    this.root.className='survival-panel';this.root.hidden=true;parent.append(this.root);
    this.root.addEventListener('dragstart',e=>{const t=(e.target as HTMLElement).closest<HTMLElement>('[data-slot]');if(t){this.drag={container:t.dataset.container as SlotRef['container'],slot:Number(t.dataset.slot)};this.split=(e as DragEvent).shiftKey;(e as DragEvent).dataTransfer?.setData('text/plain',JSON.stringify(this.drag));}});
    this.root.addEventListener('dragover',e=>e.preventDefault());this.root.addEventListener('drop',e=>{e.preventDefault();const t=(e.target as HTMLElement).closest<HTMLElement>('[data-slot]');if(t&&this.drag&&this.station)this.actions.move(this.station.id,this.drag,{container:t.dataset.container as SlotRef['container'],slot:Number(t.dataset.slot)},this.split||(e as DragEvent).shiftKey);this.drag=null;this.hash='';});this.root.addEventListener('dragend',()=>this.drag=null);
    this.root.addEventListener('click',e=>{const a=(e.target as HTMLElement).closest<HTMLElement>('[data-action]')?.dataset.action;if(a==='close')this.actions.close();if(!this.station)return;if(a==='take')this.actions.takeAll(this.station.id);if(a==='toggle')this.actions.toggle(this.station.id);if(a==='spawn')this.actions.spawn(this.station.id);if(a==='techTree')this.actions.openTechTree(this.station.id);this.hash='';});
  }
  get isOpen(){return !this.root.hidden;}
  open(s:Station,p:(ItemStack|null)[],stations:Station[]=[s],structures:Structure[]=[]){this.root.hidden=false;this.hash='';this.powerCheckAt=0;this.structures=structures;this.update(s,p,stations);}
  close(){this.root.hidden=true;this.station=null;this.drag=null;}
  private label(s:Station,index:number,container:string,cs=false){if(container!=='station')return String(index+1);if(s.kind==='furnace')return index<2?stationText(cs,'INPUT','VSTUP'):index===2?stationText(cs,'FUEL','PALIVO'):stationText(cs,'OUTPUT','VÝSTUP');if(s.kind==='campfire')return index===0?stationText(cs,'FUEL','PALIVO'):index===1?stationText(cs,'RAW MEAT','SYROVÉ MASO'):stationText(cs,'OUTPUT','VÝSTUP');if(s.kind==='generator')return stationText(cs,'FUEL','PALIVO');if(s.kind==='recycler')return index<3?stationText(cs,'INPUT','VSTUP'):stationText(cs,'OUTPUT','VÝSTUP');return String(index+1);}
  update(s:Station,p:(ItemStack|null)[],stations:Station[]=[s]){
    this.station=s;if(performance.now()-this.powerCheckAt>=250){this.poweredLamps=poweredLampIds(stations);this.poweredHomesteads=poweredHomesteadIds(stations);this.powerCheckAt=performance.now();}const powered=s.kind==='lamp'&&this.poweredLamps.has(s.id),securityPowered=s.kind==='homesteadCore'&&this.poweredHomesteads.has(s.id),claimed=s.kind==='homesteadCore'?this.structures.filter(item=>Math.hypot(item.position.x-s.position.x,item.position.z-s.position.z)<=HOMESTEAD_RADIUS):[],lockedDoors=claimed.filter(item=>item.pieceType==='door'&&item.locked).length,hash=JSON.stringify([s.inventory,p,s.active,s.job&&Math.ceil(s.job.remaining),powered,securityPowered,claimed.length,lockedDoors]);if(hash===this.hash||this.drag)return;this.hash=hash;
    const language=document.documentElement.lang==='cs'?'cs':'en',cs=language==='cs',t=(en:string,cz:string)=>stationText(cs,en,cz);
    const slots=(items:(ItemStack|null)[],container:string)=>items.map((x,i)=>{const name=x?itemName(x.itemId,language):cs?'Prázdné':'Empty';return `<button class="station-slot ${container==='station'&&isStationOutputSlot(s,i)?'station-output':''}" draggable="${!!x}" data-container="${container}" data-slot="${i}" title="${name}"><small>${this.label(s,i,container,cs)}</small>${x?`<img draggable="false" src="${ITEMS[x.itemId].icon}" alt="${name}"><b>${x.count}</b>`:''}</button>`;}).join('');
    const processing=['furnace','campfire','recycler','generator','powerSwitch'].includes(s.kind),recipe=currentRecyclerRecipe(s),status=s.kind==='lamp'?(powered?t('POWERED · SWITCH ONLINE','NAPÁJENO · VYPÍNAČ ZAPNUT'):t('NO POWER · CHECK GENERATOR / SWITCH','BEZ NAPÁJENÍ · ZKONTROLUJ GENERÁTOR / VYPÍNAČ')):stationStatus(s),statusText:Record<string,[string,string]>={OFF:['OFF','VYPNUTO'],ON:['ON','ZAPNUTO'],BLOCKED_NO_FUEL:['NO FUEL','CHYBÍ PALIVO'],BLOCKED_NO_INPUT:['NO INPUT','CHYBÍ VSTUP'],BLOCKED_OUTPUT_FULL:['OUTPUT FULL','VÝSTUP JE PLNÝ'],PROCESSING:['PROCESSING','ZPRACOVÁVÁ SE']},localizedStatus=(value:string)=>{const pair=statusText[value];return pair?t(pair[0],pair[1]):value.replaceAll('_',' ');},recyclerDetail=s.kind==='recycler'?(s.job&&recipe?`${t('PROCESSING','ZPRACOVÁVÁ SE')} · ${itemName(recipe.input,language).toUpperCase()} · ${Math.ceil(s.job.remaining)}s`:status==='BLOCKED_OUTPUT_FULL'?t('OUTPUT FULL','VÝSTUP JE PLNÝ'):status==='BLOCKED_NO_INPUT'?t('READY · NO SALVAGE INPUT','PŘIPRAVENO · VLOŽ ZÁSOHY'):t('READY','PŘIPRAVENO')):'';
    const heading=s.kind==='furnace'?t('PROCESSING · 10 RAW + 5 FUEL → 10 FRAGMENTS','TAVENÍ · 10 RUDY + 5 PALIVA → 10 KOVŮ'):s.kind==='campfire'?t('COOKING · 1 RAW MEAT + 1 WOOD → 1 COOKED','VAŘENÍ · 1 SYROVÉ MASO + 1 DŘEVO → 1 HOTOVÉ'):s.kind==='recycler'?t('RECYCLING · COMPONENTS → SCRAP + METAL','RECYKLACE · SOUČÁSTKY → ŠROT + KOV'):s.kind==='generator'?t('GENERATOR FUEL · WOOD','PALIVO GENERÁTORU · DŘEVO'):t('CONTENTS','OBSAH');
    const level=s.kind.startsWith('workbench')?Number(s.kind.slice(-1)):0,descriptions:Partial<Record<Station['kind'],[string,string]>>={campfire:['Add wood and raw meat, then leave the fire running. One piece cooks in 12 seconds; cooked meat appears in OUTPUT.','Vlož dřevo a syrové maso a nech oheň hořet. Jeden kus se upeče za 12 sekund; hotové maso se objeví ve VÝSTUPU.'],recycler:['Feed recovered components into protected input slots. Outputs save with your world.','Vkládej nalezené součástky do chráněných vstupů. Výstupy se ukládají se světem.'],generator:['Burns one wood every two minutes while running. A nearby active switch routes power to lamps and Homestead Beacons.','Za chodu spálí jedno dřevo za dvě minuty. Blízký zapnutý vypínač přivede proud ke svítilnám a majetkovým majákům.'],powerSwitch:['Connects a fueled generator to utility lamps or a Homestead Beacon within 11 meters.','Propojí zásuvný generátor se svítilnami nebo majetkovým majákem do vzdálenosti 11 metrů.'],lamp:['Automatically lights when a fueled generator and active switch are in local range.','Rozsvítí se, když je poblíž generátor s palivem a zapnutý vypínač.'],homesteadCore:[`SECURITY ${securityPowered?'ARMED · POWERED':'OFF · CONNECT GENERATOR / SWITCH'} · Property radius ${HOMESTEAD_RADIUS} m · ${claimed.length} structures · ${lockedDoors} secured doors. Existing closed doors and new doors in this area lock automatically.`,`OCHRANA ${securityPowered?'AKTIVNÍ · NAPÁJENÁ':'VYPNUTÁ · PŘIPOJ GENERÁTOR / VYPÍNAČ'} · Poloměr území ${HOMESTEAD_RADIUS} m · staveb: ${claimed.length} · zamčených dveří: ${lockedDoors}. Zavřené i nové dveře v této oblasti se automaticky zamykají.`]};
    const description=descriptions[s.kind]?.[cs?1:0]??(level?t(`Workbench level ${level} · Crafting tier ${level} · Research up to tier ${level}`,`Pracovní stůl úrovně ${level} · Výroba úrovně ${level} · Výzkum do úrovně ${level}`):t('Drag to transfer or swap · Shift-drag to split · Contents save with your world','Přetáhni předměty pro přesun nebo výměnu · Shift+tažení rozdělí stack · Obsah se ukládá se světem'));
    this.root.innerHTML=`<header><span>TIDELAND / ${t('FIELD EQUIPMENT','POLNÍ VYBAVENÍ')}</span><button data-action="close">${t('CLOSE · ESC','ZAVŘÍT · ESC')}</button></header><h1>${stationNames[s.kind][cs?1:0]}</h1><p>${description}</p><div class="station-columns"><section><h2>${t('YOUR INVENTORY','TVŮJ INVENTÁŘ')}</h2><div class="station-grid">${slots(p,'player')}</div></section><section><h2>${heading}</h2><div class="station-grid">${slots(s.inventory,'station')}</div>${s.kind==='lamp'?`<p data-status>${status}</p>`:''}${s.inventory.some(Boolean)?`<button data-action="take">${t('TAKE ALL','VZÍT VŠE')}</button>`:''}${processing?`<p data-status>${s.kind==='recycler'?recyclerDetail:localizedStatus(status)+(s.job?` · ${Math.ceil(s.job.remaining)}s`:'')}</p><button data-action="toggle">${s.active?(s.kind==='recycler'?t('STOP RECYCLER','ZASTAVIT RECYKLÉR'):t('TURN OFF','VYPNOUT')):(s.kind==='recycler'?t('START RECYCLER','ZAPNOUT RECYKLÉR'):t('TURN ON','ZAPNOUT'))}</button>`:''}${s.kind==='bedroll'?`<button data-action="spawn">${t('SET RESPAWN POINT','NASTAVIT MÍSTO OBNOVENÍ')}</button>`:''}${s.kind.startsWith('workbench')?`<p>${t('Scrap carried:','Šrot u sebe:')} ${p.reduce((n,x)=>n+(x?.itemId==='scrap'?x.count:0),0)}</p><button class="workbench-research-button" data-action="techTree">${t('OPEN TECH TREE','OTEVŘÍT STROM VÝZKUMU')}</button>`:''}</section></div>`;
  }
}
