import * as T from 'three';import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';import {flameMaterial} from '../rendering/Flame';import {woodMaterial,stoneMaterial} from '../rendering/materials';import {STATIONS,type Station,poweredHomesteadIds,poweredLampIds,stationStatus} from './stations';import type {CollisionBox} from '../physics/PhysicsWorld';
export class StationRenderer {
 readonly objects=new Map<string,T.Group>();readonly group=new T.Group();readonly ghost=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial({color:0x8cb397,transparent:true,opacity:.35,depthWrite:false}));
 private interaction=new T.MeshBasicMaterial({visible:false});
 private poweredLamps=new Set<string>();private poweredBeacons=new Set<string>();private lastPowerRefresh=-1;
 private collapsing=new Map<string,{startedAt:number|null;group:T.Group;parts:{object:T.Object3D;position:T.Vector3;rotation:T.Euler;direction:T.Vector3;spin:T.Vector3}[]}>();
 private wood=woodMaterial('#716451');private stone=stoneMaterial();private iron=new T.MeshStandardMaterial({color:0x545b59,roughness:.8,metalness:.35});private cloth=new T.MeshStandardMaterial({color:0x626b52,roughness:1});private signal=new T.MeshStandardMaterial({color:0x274f42,emissive:0x62e3a8,emissiveIntensity:2.4,roughness:.55});private alarmSignal=new T.MeshStandardMaterial({color:0x6f201a,emissive:0xff3222,emissiveIntensity:3.2,roughness:.5});private inactiveSignal=new T.MeshStandardMaterial({color:0x28302b,emissive:0x000000,roughness:.8});private lampGlass=new T.MeshStandardMaterial({color:0xffe1a1,emissive:0xffcf78,emissiveIntensity:3,roughness:.35});private fire=flameMaterial();private lights=[new T.PointLight(0xffc394,0,10,2),new T.PointLight(0xffc394,0,10,2)];
 constructor(scene:T.Scene){scene.add(this.group,this.ghost,...this.lights);this.ghost.visible=false;}
 private box(g:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,m:T.Material){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;g.add(mesh);return mesh;}
 private make(s:Station){const g=new T.Group(),[w,h,d]=STATIONS[s.kind].size;
 if(s.kind==='deathbag'){const body=new T.Mesh(new T.CapsuleGeometry(.31,.48,4,10),this.cloth);body.rotation.z=Math.PI/2;body.scale.z=1.15;body.position.y=.31;body.castShadow=body.receiveShadow=true;g.add(body);for(const x of [-.28,.28]){const strap=new T.Mesh(new T.TorusGeometry(.32,.025,5,12,Math.PI*1.25),this.wood);strap.rotation.set(Math.PI/2,0,Math.PI/2);strap.position.set(x,.34,.04);g.add(strap);}this.box(g,0,.36,.43,.28,.14,.045,this.wood);this.box(g,0,.36,.465,.1,.07,.025,this.iron);const roll=new T.Mesh(new T.CylinderGeometry(.13,.13,.72,10),this.cloth);roll.rotation.z=Math.PI/2;roll.position.set(0,.55,-.23);g.add(roll);}
 else if(s.kind==='recycler'){const drum=new T.Mesh(new T.CylinderGeometry(.49,.54,.9,12),this.iron);drum.rotation.z=Math.PI/2;drum.position.set(-.1,.82,0);drum.castShadow=drum.receiveShadow=true;g.add(drum);for(const x of [-.48,.28]){const ring=new T.Mesh(new T.TorusGeometry(.5,.045,6,12),this.iron);ring.rotation.y=Math.PI/2;ring.position.set(x,.82,0);g.add(ring);}const drive=new T.Group();drive.name='recycler-drive';drive.position.set(.67,.86,-.36);const wheel=new T.Mesh(new T.CylinderGeometry(.27,.27,.13,10),this.iron);wheel.rotation.z=Math.PI/2;drive.add(wheel);for(let i=0;i<6;i++){const tooth=this.box(drive,0,Math.cos(i*Math.PI/3)*.31,Math.sin(i*Math.PI/3)*.31,.15,.12,.12,this.iron);tooth.rotation.x=i*Math.PI/3;}g.add(drive);this.box(g,-.12,.33,.58,1.35,.11,.62,this.iron).rotation.x=-.14;this.box(g,.65,.43,.46,.55,.18,.46,this.wood);this.box(g,.62,.72,.53,.48,.72,.12,this.iron);const light=this.box(g,.62,.92,.605,.12,.12,.025,this.signal);light.name='recycler-light';this.box(g,-.66,.25,-.4,.3,.5,.3,this.iron);}
 else if(s.kind==='secureCache'){this.box(g,0,h*.42,0,w-.12,h*.68,d-.1,this.iron);this.box(g,0,h*.84,0,w,h*.18,d,this.wood);for(const x of [-.43,.43]){this.box(g,x,h*.52,d/2+.015,.09,.54,.05,this.iron);this.box(g,x,h*.84,d/2+.018,.12,.12,.06,this.iron);}const latch=this.box(g,0,h*.57,d/2+.05,.22,.26,.09,this.iron);latch.name='sealed-cache-latch';}
 else if(s.kind==='storage'||s.kind==='loot'){for(let i=0;i<6;i++){this.box(g,-w/2+w*(i+.5)/6,h/2,0,w/6-.018,h,d,this.wood);}for(const x of [-w*.36,w*.36]){this.box(g,x,h+.015,0,.08,.04,d+.03,this.iron);for(const z of [-d/2,d/2])this.box(g,x,h/2,z,.07,h,.025,this.iron);}this.box(g,0,h*.7,d/2+.02,.15,.13,.04,this.iron);if(s.id==='event-radio-signal'){const mast=new T.Mesh(new T.CylinderGeometry(.025,.04,.68,6),this.iron);mast.name='Relay cache aerial';mast.position.set(0,h+.34,0);mast.castShadow=true;g.add(mast);const beacon=new T.Mesh(new T.SphereGeometry(.095,8,6),this.signal);beacon.name='Relay cache signal light';beacon.position.set(0,h+.72,0);g.add(beacon);}}
 else if(s.kind.startsWith('workbench')){for(const x of [-.72,.72])for(const z of [-.28,.28])this.box(g,x,.43,z,.11,.86,.11,this.wood);this.box(g,0,.92,0,w,.16,d,this.wood);this.box(g,0,.2,0,w-.15,.08,d-.1,this.wood);this.box(g,-.48,1.12,0,.25,.25,.24,this.iron);const level=Number(s.kind.slice(-1));for(let i=0;i<level;i++)this.box(g,.1+i*.22,1.05,0,.12,.13,.5,this.iron);if(level>1){this.box(g,0,1.48,-.35,1.6,.7,.06,this.wood);for(let i=0;i<5;i++)this.box(g,-.6+i*.3,1.5,-.3,.05,.35,.035,this.iron);}}
 else if(s.kind==='generator'){this.box(g,0,.16,0,.88,.24,.6,this.iron);this.box(g,0,.48,0,.68,.42,.48,this.wood);this.box(g,0,.48,.25,.38,.2,.035,this.iron);this.box(g,-.3,.23,-.2,.12,.3,.12,this.iron);const meter=this.box(g,.23,.59,.273,.12,.1,.025,this.signal);meter.name='generator-light';}
 else if(s.kind==='powerSwitch'){this.box(g,0,.04,0,.34,.08,.27,this.iron);this.box(g,0,.4,0,.24,.68,.19,this.wood);this.box(g,0,.48,.105,.14,.25,.035,this.iron);const toggle=this.box(g,0,.49,.14,.055,.15,.035,this.signal);toggle.name='switch-toggle';}
 else if(s.kind==='lamp'){this.box(g,0,.06,0,.4,.12,.4,this.iron);this.box(g,0,.86,0,.09,1.52,.09,this.iron);this.box(g,0,1.62,0,.34,.12,.34,this.iron);const bulb=new T.Mesh(new T.SphereGeometry(.105,8,6),this.lampGlass);bulb.position.set(0,1.43,0);bulb.name='power-lamp-bulb';g.add(bulb);for(const x of [-.16,.16])this.box(g,x,1.43,0,.025,.43,.025,this.iron);}
 else if(s.kind==='homesteadCore'){this.box(g,0,.10,0,.76,.20,.76,this.iron);const mast=new T.Mesh(new T.CylinderGeometry(.055,.09,1.38,8),this.iron);mast.position.y=.87;mast.castShadow=true;g.add(mast);const beacon=new T.Mesh(new T.OctahedronGeometry(.22,0),this.signal);beacon.position.y=1.62;beacon.name='homestead-beacon-light';beacon.castShadow=true;g.add(beacon);this.box(g,0,.34,.40,.32,.30,.07,this.wood);this.box(g,0,.35,.445,.14,.12,.025,this.signal);}
 else if(s.kind==='bedroll'){this.box(g,0,.08,0,.85,.16,1.9,this.cloth);const roll=new T.Mesh(new T.CylinderGeometry(.17,.17,.78,12),this.cloth);roll.rotation.z=Math.PI/2;roll.position.set(0,.23,-.68);g.add(roll);for(const x of [-.29,.29])this.box(g,x,.17,0,.035,.025,1.9,this.wood);}
 else {if(s.kind==='furnace'){const shell=new T.Mesh(new T.CylinderGeometry(.43,.56,1.3,10,1,true),this.stone);shell.position.y=.65;g.add(shell);this.box(g,0,1.4,0,.34,.4,.34,this.iron);this.box(g,0,.37,.53,.52,.5,.04,this.iron);}else for(let i=0;i<9;i++){const stone=new T.Mesh(new T.DodecahedronGeometry(.16),this.stone);stone.position.set(Math.cos(i*7)*.45,.11,Math.sin(i*7)*.45);g.add(stone);}for(let i=0;i<3;i++){const log=this.box(g,0,.13,0,.13,.13,.7,this.wood);log.rotation.y=i*Math.PI/3;}for(let i=0;i<3;i++){const f=new T.Mesh(new T.PlaneGeometry(.32,.65),this.fire);f.position.set((i-1)*.09,.47,s.kind==='furnace'?.56:0);f.rotation.y=i*Math.PI/3;f.name='flame';g.add(f);}}
 if(s.id==='loot-poi-4'||s.id==='secure-cache-poi-4')this.mergeStaticStationMeshes(g,s.id);
 this.box(g,0,h/2,0,w,h,d,this.interaction);
 g.position.set(s.position.x,s.position.y,s.position.z);g.rotation.y=s.rotation;g.traverse(o=>o.userData.stationId=s.id);return g;}
 private mergeStaticStationMeshes(group:T.Group,id:string){
  type Batch={material:T.Material;castShadow:boolean;receiveShadow:boolean;geometries:T.BufferGeometry[];markers:{name:string;position:T.Vector3}[]};
  const batches=new Map<string,Batch>();
  for(const child of [...group.children]){if(!(child instanceof T.Mesh)||Array.isArray(child.material))continue;child.updateMatrix();const key=`${child.material.uuid}:${child.castShadow}:${child.receiveShadow}`;let batch=batches.get(key);if(!batch){batch={material:child.material,castShadow:child.castShadow,receiveShadow:child.receiveShadow,geometries:[],markers:[]};batches.set(key,batch);}const geometry=child.geometry.clone();geometry.applyMatrix4(child.matrix);batch.geometries.push(geometry);if(child.name)batch.markers.push({name:child.name,position:child.position.clone()});group.remove(child);child.geometry.dispose();}
  let index=0;for(const batch of batches.values()){const geometry=mergeGeometries(batch.geometries,false);batch.geometries.forEach(part=>part.dispose());if(!geometry)throw new Error(`Could not batch static station geometry: ${id}`);geometry.computeBoundingBox();geometry.computeBoundingSphere();const mesh=new T.Mesh(geometry,batch.material);mesh.name=`${id}-batched-shell-${index++}`;mesh.castShadow=batch.castShadow;mesh.receiveShadow=batch.receiveShadow;group.add(mesh);for(const marker of batch.markers){const feature=new T.Object3D();feature.name=marker.name;feature.position.copy(marker.position);group.add(feature);}}
 }
 sync(stations:Station[]){const ids=new Set(stations.map(s=>s.id));for(const [id,o]of this.objects)if(!ids.has(id)&&!this.collapsing.has(id)){this.disposeObject(o);this.objects.delete(id);}for(const s of stations)if(!this.objects.has(s.id)){const g=this.make(s);this.objects.set(s.id,g);this.group.add(g);}}
 update(stations:Station[],time:number,p:T.Vector3,alarms:ReadonlySet<string>=new Set()){this.fire.uniforms.time.value=time;if(time-this.lastPowerRefresh>=.2){this.poweredLamps=stations.some(s=>s.kind==='lamp')?poweredLampIds(stations):new Set<string>();this.poweredBeacons=stations.some(s=>s.kind==='homesteadCore')?poweredHomesteadIds(stations):new Set<string>();this.lastPowerRefresh=time;}const powered=this.poweredLamps;let lit=0;for(const s of stations){const active=stationStatus(s)==='PROCESSING',g=this.objects.get(s.id);g?.traverse(o=>{if(o.name==='flame'){o.visible=active;o.scale.set(1+.12*Math.sin(time*8+o.id),.8+.24*Math.sin(time*5+o.id),1);o.rotation.y=time*.3+o.id;}else if(o.name==='recycler-drive'&&active){o.rotation.x=time*2.8;o.position.y=.86+Math.sin(time*18)*.008;}else if(o.name==='recycler-light')o.visible=active;else if(o.name==='switch-toggle')o.rotation.x=s.active?-.45:.45;else if(o.name==='generator-light')o.visible=s.active&&stationStatus(s)==='ON';else if(o.name==='power-lamp-bulb')o.visible=powered.has(s.id);else if(o.name==='homestead-beacon-light'&&o instanceof T.Mesh){o.material=alarms.has(s.id)?this.alarmSignal:this.poweredBeacons.has(s.id)?this.signal:this.inactiveSignal;o.visible=!alarms.has(s.id)||Math.sin(time*11)>-.55;}});const dx=p.x-s.position.x,dy=p.y-s.position.y,dz=p.z-s.position.z;if((active||powered.has(s.id))&&s.kind!=='recycler'&&lit<2&&dx*dx+dy*dy+dz*dz<324){const l=this.lights[lit++];l.position.set(s.position.x,s.position.y+.65,s.position.z);l.intensity=5+Math.sin(time*4)*.4;}}for(let i=lit;i<2;i++)this.lights[i].intensity=0;for(const [id,fx] of [...this.collapsing]){if(fx.startedAt===null)fx.startedAt=time;const elapsed=Math.max(0,time-fx.startedAt),t=Math.min(1,elapsed/.72),burst=1-Math.pow(1-t,2),shrink=Math.max(.025,1-Math.pow(t,2.35));for(const part of fx.parts){part.object.position.copy(part.position).addScaledVector(part.direction,burst);part.object.position.y+=Math.sin(Math.PI*t)*.28-t*t*.72;part.object.rotation.set(part.rotation.x+part.spin.x*t,part.rotation.y+part.spin.y*t,part.rotation.z+part.spin.z*t);part.object.scale.setScalar(shrink);}if(t>=1){this.collapsing.delete(id);this.disposeObject(fx.group);this.objects.delete(id);}}}
 collapseContainer(id:string):boolean{const group=this.objects.get(id);if(!group||this.collapsing.has(id))return false;const parts=group.children.filter((object):object is T.Mesh=>object instanceof T.Mesh&&object.material!==this.interaction).map((object,index)=>{const angle=.55+index*2.399963,direction=new T.Vector3(Math.cos(angle),.48+(index%3)*.13,Math.sin(angle)).normalize().multiplyScalar(.72+(index%4)*.17),spin=new T.Vector3((index%2?1:-1)*(.45+(index%3)*.18),(.5+(index%4)*.22)*(index%2?-1:1),(.35+(index%5)*.13)*(index%3?-1:1));return {object,position:object.position.clone(),rotation:object.rotation.clone(),direction,spin};});if(!parts.length)return false;this.collapsing.set(id,{startedAt:null,group,parts});return true;}
 collapseLoot(id:string):boolean{return this.collapseContainer(id);}
 boxes(s:Station):CollisionBox[]{const [w,h,d]=STATIONS[s.kind].size;return [{position:{x:s.position.x,y:s.position.y+h/2,z:s.position.z},halfExtents:{x:w/2,y:h/2,z:d/2},rotation:s.rotation}];}
 preview(kind:Station['kind']|null,p?:T.Vector3,rotation=0,valid=true){this.ghost.visible=!!kind&&!!p;if(kind&&p){const [w,h,d]=STATIONS[kind].size;this.ghost.scale.set(w,h,d);this.ghost.position.copy(p);this.ghost.position.y+=h/2;this.ghost.rotation.y=rotation;this.ghost.material.color.set(valid?0x8cb397:0xcd685a);}}
 private disposeObject(o:T.Object3D){o.traverse(x=>{if(x instanceof T.Mesh)x.geometry.dispose();});o.removeFromParent();}
 dispose(){this.disposeObject(this.group);this.disposeObject(this.ghost);this.lights.forEach(l=>l.removeFromParent());[this.wood,this.stone,this.iron,this.cloth,this.signal,this.alarmSignal,this.inactiveSignal,this.lampGlass,this.fire,this.ghost.material,this.interaction].forEach(m=>m.dispose());}
}
