import {ITEMS} from '../items/definitions';
import type {ItemStack,Structure} from '../core/types';
import {currentRecyclerRecipe,HOMESTEAD_RADIUS,isStationOutputSlot,poweredHomesteadIds,poweredLampIds,STATIONS,stationStatus,type Station,type SlotRef} from './stations';
import './survival.css';

export class StationUI {
  readonly root=document.createElement('section');private station:Station|null=null;private drag:SlotRef|null=null;private split=false;private hash='';private powerCheckAt=0;private poweredLamps=new Set<string>();private poweredHomesteads=new Set<string>();private structures:Structure[]=[];
  constructor(parent:HTMLElement,private actions:{move:(id:string,a:SlotRef,b:SlotRef,split:boolean)=>void;takeAll:(id:string)=>void;toggle:(id:string)=>void;spawn:(id:string)=>void;openTechTree:(id:string)=>void;close:()=>void}){
    this.root.className='survival-panel';this.root.hidden=true;parent.append(this.root);
    this.root.addEventListener('dragstart',e=>{const t=(e.target as HTMLElement).closest<HTMLElement>('[data-slot]');if(t){this.drag={container:t.dataset.container as SlotRef['container'],slot:Number(t.dataset.slot)};this.split=(e as DragEvent).shiftKey;(e as DragEvent).dataTransfer?.setData('text/plain',JSON.stringify(this.drag));}});
    this.root.addEventListener('dragover',e=>e.preventDefault());this.root.addEventListener('drop',e=>{e.preventDefault();const t=(e.target as HTMLElement).closest<HTMLElement>('[data-slot]');if(t&&this.drag&&this.station)this.actions.move(this.station.id,this.drag,{container:t.dataset.container as SlotRef['container'],slot:Number(t.dataset.slot)},this.split||(e as DragEvent).shiftKey);this.drag=null;this.hash='';});this.root.addEventListener('dragend',()=>this.drag=null);
    this.root.addEventListener('click',e=>{const a=(e.target as HTMLElement).closest<HTMLElement>('[data-action]')?.dataset.action;if(a==='close')this.actions.close();if(!this.station)return;if(a==='take')this.actions.takeAll(this.station.id);if(a==='toggle')this.actions.toggle(this.station.id);if(a==='spawn')this.actions.spawn(this.station.id);if(a==='techTree')this.actions.openTechTree(this.station.id);this.hash='';});
  }
  get isOpen(){return !this.root.hidden;}
  open(s:Station,p:(ItemStack|null)[],stations:Station[]=[s],structures:Structure[]=[]){this.root.hidden=false;this.hash='';this.powerCheckAt=0;this.structures=structures;this.update(s,p,stations);}
  close(){this.root.hidden=true;this.station=null;this.drag=null;}
  private label(s:Station,index:number,container:string){if(container!=='station')return String(index+1);if(s.kind==='furnace')return index<2?'INPUT':index===2?'FUEL':'OUTPUT';if(s.kind==='generator')return 'FUEL';if(s.kind==='recycler')return index<3?'INPUT':'OUTPUT';return String(index+1);}
  update(s:Station,p:(ItemStack|null)[],stations:Station[]=[s]){
    this.station=s;if(performance.now()-this.powerCheckAt>=250){this.poweredLamps=poweredLampIds(stations);this.poweredHomesteads=poweredHomesteadIds(stations);this.powerCheckAt=performance.now();}const powered=s.kind==='lamp'&&this.poweredLamps.has(s.id),securityPowered=s.kind==='homesteadCore'&&this.poweredHomesteads.has(s.id),claimed=s.kind==='homesteadCore'?this.structures.filter(item=>Math.hypot(item.position.x-s.position.x,item.position.z-s.position.z)<=HOMESTEAD_RADIUS):[],lockedDoors=claimed.filter(item=>item.pieceType==='door'&&item.locked).length,hash=JSON.stringify([s.inventory,p,s.active,s.job&&Math.ceil(s.job.remaining*10),powered,securityPowered,claimed.length,lockedDoors]);if(hash===this.hash||this.drag)return;this.hash=hash;
    const slots=(items:(ItemStack|null)[],container:string)=>items.map((x,i)=>`<button class="station-slot ${container==='station'&&isStationOutputSlot(s,i)?'station-output':''}" draggable="${!!x}" data-container="${container}" data-slot="${i}" title="${x?ITEMS[x.itemId].displayName:'Empty'}"><small>${this.label(s,i,container)}</small>${x?`<img draggable="false" src="${ITEMS[x.itemId].icon}" alt="${ITEMS[x.itemId].displayName}"><b>${x.count}</b>`:''}</button>`).join('');
    const processing=['furnace','campfire','recycler','generator','powerSwitch'].includes(s.kind),recipe=currentRecyclerRecipe(s),status=s.kind==='lamp'?(powered?'POWERED · SWITCH ONLINE':'NO POWER · CHECK GENERATOR / SWITCH'):stationStatus(s),recyclerDetail=s.kind==='recycler'?(s.job&&recipe?`PROCESSING · ${ITEMS[recipe.input].displayName.toUpperCase()} · ${Math.ceil(s.job.remaining)}s`:status==='BLOCKED_OUTPUT_FULL'?'OUTPUT FULL':status==='BLOCKED_NO_INPUT'?'READY · NO SALVAGE INPUT':'READY'):'';
    const heading=s.kind==='furnace'?'PROCESSING · 10 RAW + 5 FUEL → 10 FRAGMENTS':s.kind==='recycler'?'RECYCLING · COMPONENTS → SCRAP + METAL':s.kind==='generator'?'GENERATOR FUEL · WOOD':'CONTENTS';
    const level=s.kind.startsWith('workbench')?Number(s.kind.slice(-1)):0;this.root.innerHTML=`<header><span>TIDELAND / FIELD EQUIPMENT</span><button data-action="close">CLOSE · ESC</button></header><h1>${STATIONS[s.kind].name}</h1><p>${s.kind==='recycler'?'Feed recovered components into protected input slots. Outputs save with your world.':s.kind==='generator'?'Burns one wood every two minutes while running. A nearby active switch routes power to lamps and Homestead Beacons.':s.kind==='powerSwitch'?'Connects a fueled generator to utility lamps or a Homestead Beacon within 11 meters.':s.kind==='lamp'?'Automatically lights when a fueled generator and active switch are in local range.':s.kind==='homesteadCore'?`SECURITY ${securityPowered?'ARMED · POWERED':'OFF · CONNECT GENERATOR / SWITCH'} · Property radius ${HOMESTEAD_RADIUS} m · ${claimed.length} structures · ${lockedDoors} secured doors. Existing closed doors and new doors in this area lock automatically.`:s.kind.startsWith('workbench')?`Workbench level ${level} · Crafting tier ${level} · Research up to tier ${level}`:'Drag to transfer or swap · Shift-drag to split · Contents save with your world'}</p><div class="station-columns"><section><h2>YOUR INVENTORY</h2><div class="station-grid">${slots(p,'player')}</div></section><section><h2>${heading}</h2><div class="station-grid">${slots(s.inventory,'station')}</div>${s.kind==='lamp'?`<p data-status>${status}</p>`:''}${s.inventory.some(Boolean)?'<button data-action="take">TAKE ALL</button>':''}${processing?`<p data-status>${s.kind==='recycler'?recyclerDetail:status.replaceAll('_',' ')+(s.job?` · ${Math.ceil(s.job.remaining)}s`:'')}</p><button data-action="toggle">${s.active?(s.kind==='recycler'?'STOP RECYCLER':'TURN OFF'):(s.kind==='recycler'?'START RECYCLER':'TURN ON')}</button>`:''}${s.kind==='bedroll'?'<button data-action="spawn">SET RESPAWN POINT</button>':''}${s.kind.startsWith('workbench')?`<p>Scrap carried: ${p.reduce((n,x)=>n+(x?.itemId==='scrap'?x.count:0),0)}</p><button class="workbench-research-button" data-action="techTree">OPEN TECH TREE</button>`:''}</section></div>`;
  }
}
