import * as T from 'three';import type {GameState} from '../core/types';import type {Atmosphere} from '../world/atmosphere';import {ensureProgression} from './progression';
export const WEATHER=['clear','rain','fog','storm'] as const;
const WEATHER_FOG_TINT=new T.Color(0x89989a);
export function stormLightningRoll(seed:number,bucket:number):number{const value=Math.sin(seed*.000173+bucket*127.1)*43758.5453;return value-Math.floor(value);}
export function rainStreakLength(index:number,storm:number):number{return .34+(index%11)*.025+storm*.16;}
export class Weather {
 private geometry=new T.BufferGeometry();private material=new T.LineBasicMaterial({color:0xa9c0c8,transparent:true,opacity:0,depthWrite:false});private rain:T.LineSegments;private positions=new Float32Array(1800*6);private t=0;private lightningRemaining=0;private lightningPeak=0;private lightningBucket=-1;
 constructor(scene:T.Scene){for(let i=0;i<1800;i++){const x=Math.sin(i*78.21)*22,z=Math.sin(i*43.57)*22,y=(i*1.731)%19;this.positions.set([x,y,z,x+.08,y+.7,z+.03],i*6);}this.geometry.setAttribute('position',new T.BufferAttribute(this.positions,3));this.rain=new T.LineSegments(this.geometry,this.material);this.rain.frustumCulled=false;scene.add(this.rain);}
 update(dt:number,state:GameState,a:Atmosphere,p:T.Vector3,quality:string){const w=ensureProgression(state).weather;w.remaining-=dt;if(w.remaining<=0){const ix=Math.floor(Math.abs(Math.sin(state.seed+state.elapsed*.013))*4);w.kind=WEATHER[ix];w.remaining=180+Math.abs(Math.sin(state.elapsed))*180;}w.blend=T.MathUtils.damp(w.blend,w.kind==='clear'?0:1,0.3,dt);const rain=T.MathUtils.damp(w.rain??0,(w.kind==='rain'||w.kind==='storm')?1:0,.3,dt),storm=T.MathUtils.damp(w.storm??0,w.kind==='storm'?1:0,.3,dt),fog=T.MathUtils.damp(w.mist??0,w.kind==='fog'?1:0,.3,dt);w.rain=rain;w.storm=storm;w.mist=fog;const bucket=Math.floor(state.elapsed/11);if(w.kind==='storm'){if(bucket!==this.lightningBucket){this.lightningBucket=bucket;const roll=stormLightningRoll(state.seed,bucket);if(roll>.88){this.lightningRemaining=.20;this.lightningPeak=.28+roll*.26;}}}else this.lightningRemaining=0;const lightning=this.lightningRemaining>0?this.lightningPeak*Math.sin((1-this.lightningRemaining/.20)*Math.PI):0;this.lightningRemaining=Math.max(0,this.lightningRemaining-dt);this.t+=dt*(1+storm);this.rain.visible=rain>.01;if(this.rain.visible){const attr=this.geometry.getAttribute('position'),gust=Math.sin(this.t*.19)*.45+Math.sin(this.t*.07+1.4)*.35,windX=dt*(1.4+storm*7.6+gust),windZ=dt*(.45+storm*3.1-gust*.35);for(let i=0;i<1800;i++){const index=i*6,y=((this.positions[index+1]-dt*(10+storm*8)+20)%20),x=this.positions[index]+windX,z=this.positions[index+2]+windZ;this.positions[index]=x>22?x-44:x<-22?x+44:x;this.positions[index+2]=z>22?z-44:z<-22?z+44:z;this.positions[index+1]=y;this.positions[index+3]=this.positions[index]+.08+storm*.2+windX*1.4;this.positions[index+4]=y+rainStreakLength(i,storm);this.positions[index+5]=this.positions[index+2]+.03+storm*.08+windZ*1.4;}attr.needsUpdate=true;this.geometry.setDrawRange(0,quality==='low'?700:quality==='medium'?1800:3600);this.rain.position.set(p.x,p.y-4,p.z);}this.material.opacity=rain*(.24+storm*.09);a.sun.intensity*=1-w.blend*.65-w.storm*.18;a.sun.intensity+=lightning*1.8;a.fill.intensity*=1-w.blend*.23-w.storm*.30;a.fill.intensity+=lightning*.22;a.fog.density+=fog*.012+rain*.0015+storm*.002;a.fog.color.lerp(WEATHER_FOG_TINT,w.blend*.45);a.sky.material.uniforms.lightning.value=lightning;a.sky.material.uniforms.weather.value=w.blend;a.sky.material.uniforms.storm.value=storm;a.ocean.material.uniforms.weather.value=rain*.6+storm*.4;return {rain,storm,fog,blend:w.blend,lightning,wind:1+storm*1.5};}
 dispose(){this.rain.removeFromParent();this.geometry.dispose();this.material.dispose();}}
